### PR TITLE
VDP-1375, VCDA-504: Attach VC

### PR DESCRIPTION
**Pull request by ckolovson**
VDP-1375, VCDA-504: Attach VC
- Reviewers: @sompa @anusuyar

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/194)

### CODE REVIEW

**Comment by sompa** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vc.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/194#-L64IqP8086KDYHUUNLB:-L64IqP8086KDYHUUNLC:b-vasp84) ([raw file](https://github.com/vmware/vcd-cli/blob/003183ebce9fb4a9aaa0ee44856d1380719330f4/vcd_cli/vc.py#L46)):*
> ```Python
>             --nsx-pwd 'nsx-admin-password'
>             --enable
>                 Attach Virtual Datacenter server.
> ```

Can we be more descriptive here ?  "Attaches Virtual Center(VC) server with the given credentials  to vCD"

---

*[vcd_cli/vc.py, line 125 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/194#-L64JqmAKtqOV7fEZchf:-L64JqmAKtqOV7fEZchg:b-x6t4az) ([raw file](https://github.com/vmware/vcd-cli/blob/003183ebce9fb4a9aaa0ee44856d1380719330f4/vcd_cli/vc.py#L125)):*
> ```Python
>     default=None,
>     metavar='[enable]',
>     help='enable flag (enables VC when it is attached)')
> ```

"enables VC when it is attached to vCD"

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/194)*

**Comment by sompa** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/194)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/194#-:-L64USWLL83p9ZCbHL9A:bnfp4nl)*

**Comment by ckolovson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vc.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/194#-L64IqP8086KDYHUUNLB:-L6s0tjdmX8TDqrwzwlt:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/003183ebce9fb4a9aaa0ee44856d1380719330f4/vcd_cli/vc.py#L46)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Can we be more descriptive here ?  "Attaches Virtual Center(VC) server with the given credentials  to vCD"
</blockquote></details>

Done.

---

*[vcd_cli/vc.py, line 125 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/194#-L64JqmAKtqOV7fEZchf:-L6s14ToG0c_LcJW_gUB:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/003183ebce9fb4a9aaa0ee44856d1380719330f4/vcd_cli/vc.py#L125)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

"enables VC when it is attached to vCD"
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/194)*

**Comment by sompa** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/194#-:-L6wquPVY87HQlYGt097:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/194)*

**Pull request merged**
