### PR TITLE
Add or remove rights from organization

### PR DESCRIPTION
**Pull request by sahithi**
1. Command to add new rights to a given organization.
2. Command to remove new rights from a given organization.
3. Fixed a bug in the existing command 'list-rights'. It always listed all rights available in the System instead of set of rights associated with any given organization. Fixed it as part of this change-set.
4. Added Click-remove-confirmation to one of the existing commands of role.

**Command output:**
>vcd right add 'vCenter: View' -o myOrg
>Rights added to the Org 'myOrg'

>vcd right remove 'vCenter: View' -o myOrg
>Are you sure you want to remove rights from the organization? [y/N]: y
>Rights removed from the Org 'myOrg'

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/164)

### CODE REVIEW

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/right.py, line 30 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-L35KoR0DqabJkmcey5s:-L35KoR0DqabJkmcey5t:b-kh3qpl) ([raw file](https://github.com/vmware/vcd-cli/blob/b2cc9fccaa5a7334283d2a9b10e4c3f1feee3926/vcd_cli/right.py#L30)):*
> ```Python
> 
> \b
>     Note
> ```

You can follow the docstring in vapp.py.  The contents under note can be moved under description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-:-L35MQLb_LdbxYZ6GI5-:bnfp4nl)*

**Comment by sahithi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/right.py, line 30 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-L35KoR0DqabJkmcey5s:-L35ZGeVTKO3UGQioGib:b-varttt) ([raw file](https://github.com/vmware/vcd-cli/blob/b2cc9fccaa5a7334283d2a9b10e4c3f1feee3926/vcd_cli/right.py#L30)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

You can follow the docstring in vapp.py.  The contents under note can be moved under description.
</blockquote></details>

This is a note not description. It was suggested in my previous reviews to make it a note instead of description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164)*

**Comment by anusuyar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164)*

**Comment by sompa** [comment]
*[vcd_cli/right.py, line 102 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-L3A9bL-0jhT96I2bjxu:-L3A9bL0cEHgHG2Cd17I:b5gwww4) ([raw file](https://github.com/vmware/vcd-cli/blob/b2cc9fccaa5a7334283d2a9b10e4c3f1feee3926/vcd_cli/right.py#L102)):*
> ```Python
>               required=False,
>               metavar='[org-name]',
>               help='name of the org')
> ```

Could we change this to "Name of the organization"  ? Help can have more description.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-:-L3A9v2cR_r-tGBDu-V2:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164)*

**Comment by sahithi** [comment]
Review status: 1 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/right.py, line 102 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-L3A9bL-0jhT96I2bjxu:-L3ANky6huZshmQmQgZA:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/b2cc9fccaa5a7334283d2a9b10e4c3f1feee3926/vcd_cli/right.py#L102)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Could we change this to "Name of the organization"  ? Help can have more description.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164)*

**Comment by pacogomez** [comment]
small cosmetic changes, otherwise :lgtm: 

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/right.py, line 39 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-L3AUwBC7vvTS1Cz4ZsC:-L3AUwBC7vvTS1Cz4ZsD:b-la5r0z) ([raw file](https://github.com/vmware/vcd-cli/blob/9f658f3fa15e6860c3f27867527ea230046a02cd/vcd_cli/right.py#L39)):*
> ```Python
>         vcd right list -o myOrg
>             Gets list of rights associated with the organization
> ```

remove extra lines between examples. We are also using the infinitive to describe the examples `Get` vs `Gets` see `vapp` command

---

*[vcd_cli/right.py, line 60 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-L3AW4mv8cRRNCvtGwzL:-L3AW4mwa30XfeU4Pf3u:bp4a06b) ([raw file](https://github.com/vmware/vcd-cli/blob/9f658f3fa15e6860c3f27867527ea230046a02cd/vcd_cli/right.py#L60)):*
> ```Python
> 
> 
> @right.command('list', short_help='lists rights in the current organization or System')
> ```

`list rights in...` is preferred to be consistent with the short help of the other commands, see `vcd vapp`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/164#-:-L3AWn-SJupAtve-PHoj:b-ebv5ks)*

**Pull request merged**
