### PR TITLE
Changes in vcd-cli related to the Exception Handling changes in pyvcloud

### PR DESCRIPTION
**Pull request by anusuyar**
the build error is get fixed once pyvcloud changes are checked-in.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/213)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/213#-:-LARDE8o22KE_seZ2q0N:bnfp4nl)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks failed.

---

*[vcd_cli/utils.py, line 257 at r1](https://beta.reviewable.io/reviews/vmware/vcd-cli/213#-LAUSztwD5MVY7NuQKni:-LAUSztwD5MVY7NuQKnj:bi90x2s) ([raw file](https://github.com/vmware/vcd-cli/blob/9b1c62b6ce6426a2a908fea78102b6e44640f489/vcd_cli/utils.py#L257)):*
<details><summary><i alt="summary">Quoted 11 lines of code…</i></summary>

> ```
> if type(exception) == UnauthorizedException:
>  
>         message = 'Session has expired or is invalid, please login again.'
>     elif type(exception) == AccessForbiddenException:
>         message = 'Access to the resource is forbidden, please login ' \
>                   'with the required credentials and access level.'
>     elif type(exception) == RequestTimeoutException:
>         message = 'The server timed out waiting for the request, ' \
>                   'please check your connection.'
>  
>  
> ```
</details>

Please simulate and add the test outputs here for reviewers reference.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/213)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vcd_cli/utils.py, line 257 at r1](https://beta.reviewable.io/reviews/vmware/vcd-cli/213#-LAUSztwD5MVY7NuQKni:-LAV8reF4VXlIwEPoW7W:b-e70ayn) ([raw file](https://github.com/vmware/vcd-cli/blob/9b1c62b6ce6426a2a908fea78102b6e44640f489/vcd_cli/utils.py#L257)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

> ```
> if type(exception) == UnauthorizedException:
>  
>         message = 'Session has expired or is invalid, please login again.'
>     elif type(exception) == AccessForbiddenException:
>         message = 'Access to the resource is forbidden, please login ' \
>                   'with the required credentials and access level.'
>     elif type(exception) == RequestTimeoutException:
>         message = 'The server timed out waiting for the request, ' \
>                   'please check your connection.'
>  
>  
> ```
Please simulate and add the test outputs here for reviewers reference.
</blockquote></details>

I simulated an UnauthorizedException. The output was 
Error: Session has expired or is invalid, please login again.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/213)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/213#-:-LB7Xfe19BnLgz0nv8hL:bnfp4nl)*

**Pull request merged**
