### PR TITLE
Implementing catalog update acl commands

### PR DESCRIPTION
**Pull request by anusuyar**
```
Implementing following commands

vcd catalog acl add <catalog-name> [subject:name:right]*
vcd catalog acl remove <catalog-name> [subject:name]*
vcd catalog acl share <catalog-name> --access-level ReadOnly
vcd catalog acl unshare <catalog-name>
vcd catalog acl list
vcd catalog acl info

C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd catalog acl add Test2 'org:AnuOrg1:ReadOnly'  'user:user:FullControl'
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None
AnuOrg1              org             ReadOnly
user                 user            FullControl

C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl remove Test2 'org:AnuOrg1'
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None
user                 user            FullControl

C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl remove Test2 --all
Do you want to remove all acl from the catalog 'Test2' [y/N]: y
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None


C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl share Test2
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             ReadOnly

C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl unshare Test2
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None

C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl add Test2 'org:AnuOrg1:ReadOnly'  'user:user:FullControl'
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None
AnuOrg1              org             ReadOnly
user                 user            FullControl


C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl list Test2
subject_name         subject_type    access_level
-------------------  --------------  --------------
AnuOrg (org_in_use)  org             None
anuorg1              org             ReadOnly
user                 user            FullControl

C:\sources\github\service_ecosystem\vcd-cli (master) 
(vcd-cli) λ vcd catalog acl info Test2
property                        value
------------------------------  -----------------------------------------------------------------------------------------------------
access_settings_1_access_level  ReadOnly
access_settings_1_subject_href  https://bos1-vcd-sp-static-199-204.eng.vmware.com/api/admin/org/1992f0d8-cb4a-434e-b150-a87e96ba3cd0
access_settings_1_subject_name  anuorg1
access_settings_1_subject_type  application/vnd.vmware.admin.organization+xml
access_settings_2_access_level  FullControl
access_settings_2_subject_href  https://bos1-vcd-sp-static-199-204.eng.vmware.com/api/admin/user/d69620d1-1be4-41bc-8db3-ef1006dac028
access_settings_2_subject_name  user
access_settings_2_subject_type  application/vnd.vmware.admin.user+xml
is_shared_to_everyone           False

```

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/153)

### CODE REVIEW

**Comment by sahithi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L1xIqXbSySywQZLHvvL:bbc24zz) (no related file):*
Anusuya, 

I would like to clarify few things before I review further

1. Who all can execute these commands - Sysadmin, OrgAdmin , Catalog owner? 
2. If Sys admin wants to add user1 from org1 to acl of catalog that is present in org2, will this command work now?
3. If (2) is a valid use case (or) if Catalog owner can execute the cmd, I think catalog.py (or) acl.py is the right place for add_catalog_access_settings() and other methods;  org.add_catalog_access_settings() kind of gives a different meaning to the readers.
4. If OrgAdmin (or) Catalog owner can execute this command, will the command go through if one of the acl subjects is another Organization. I think this is a security loophole.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by anusuyar** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L1yo_kx7k0ZLF89r73U:b68je2d) (no related file):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Anusuya, 

I would like to clarify few things before I review further

1. Who all can execute these commands - Sysadmin, OrgAdmin , Catalog owner? 
2. If Sys admin wants to add user1 from org1 to acl of catalog that is present in org2, will this command work now?
3. If (2) is a valid use case (or) if Catalog owner can execute the cmd, I think catalog.py (or) acl.py is the right place for add_catalog_access_settings() and other methods;  org.add_catalog_access_settings() kind of gives a different meaning to the readers.
4. If OrgAdmin (or) Catalog owner can execute this command, will the command go through if one of the acl subjects is another Organization. I think this is a security loophole.
</blockquote></details>

Regarding 2. System admin cannot add user1 from org1 when catalog is present in org2.

I get the following msg. `Sharing is only supported by an organization. `

As for 3.

I am inclined to leave add_catalog_access_settings() in org.py for now. I think it is better to move all the catalog related methods to a new file as a separate task. (As this involves lot of code changes and might break something which is already working in catalog acl)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by pacogomez** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L1zCnwOXqPM8XmA7du1:b-ikz2sy) (no related file):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Regarding 2. System admin cannot add user1 from org1 when catalog is present in org2.

I get the following msg. `Sharing is only supported by an organization. `

As for 3.

I am inclined to leave add_catalog_access_settings() in org.py for now. I think it is better to move all the catalog related methods to a new file as a separate task. (As this involves lot of code changes and might break something which is already working in catalog acl)


</blockquote></details>

in general we use the verb `create` instead of `add`. For consistency we should use `create` here too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by pacogomez** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L1zLgrHCpcU3ZccngyN:b-lhs71q) (no related file):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

in general we use the verb `create` instead of `add`. For consistency we should use `create` here too.
</blockquote></details>

same applies to `delete` instead of `remove`. For consistency we should use `delete`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by sahithi** [comment]
Review status: 0 of 2 files reviewed at latest revision, 6 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L22FWMj8YdGhShV-p4X:b-eqz62r) (no related file):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

same applies to `delete` instead of `remove`. For consistency we should use `delete`
</blockquote></details>

Okay, ensure there is a Jira task to track this pending item.

---

*[vcd_cli/catalog.py, line 408 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L22EugZ-M1ziz9wY6N9:-L22Eug_scAu2WLC4Weo:b-x53wbf) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L408)):*
> ```Python
>             specified in the format
>             '<subject-type>:<subject-name>:<access-level>'
>             subject-name is either username or org name
> ```

nit : change the order of descriptions
subject-type......
subject-name.....
access-level.......

---

*[vcd_cli/catalog.py, line 409 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L22ICUsK2XVvQa6kbtR:-L22ICUtRrJIZNOHN-wd:bzeyn3s) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L409)):*
> ```Python
>             '<subject-type>:<subject-name>:<access-level>'
>             subject-name is either username or org name
>             access-level is one 'ReadOnly', 'Change', 'FullControl'
> ```

Is it mandatory to specify access-level? If not please add some description here to indicate what are the defaults if access-level is missing.

nit: access-level is one OF

---

*[vcd_cli/catalog.py, line 415 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L22G4JTNHz7-Br_w76k:-L22G4JTNHz7-Br_w76l:bd38caj) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L415)):*
> ```Python
>             Remove one or more acl from the specified catalog. access-list is
>             specified in the format '<subject-type>:<subject-name>'
>             subject-name is either username or org name
> ```

nit: the order of sub-items in the acl

---

*[vcd_cli/catalog.py, line 466 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L22HBhF92dEnw2Iqk87:-L22HBhF92dEnw2Iqk88:b-dq3wjq) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L466)):*
> ```Python
> 
> 
> @acl.command(short_help='remove access settings from a particular catalog')
> ```

Missing confirmation prompt for removal of acl.
@click.option('-y',
              '--yes',
              is_flag=True,
              callback=abort_if_false,
              expose_value=False,
              prompt='')

---

*[vcd_cli/utils.py, line 265 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L22Hqo6ZPnlVhJXi1Qi:-L22Hqo6ZPnlVhJXi1Qj:bfjashf) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/utils.py#L265)):*
> ```Python
>         access_dict = {'type': access_setting[0], 'name': access_setting[1]}
> 
>         if len(access_setting) > 2:
> ```

Missing else block? What happens if user doesn't specify accesslevel?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by sompa** [comment]
*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L22M-g_oqXN114Bb8b6:b-hay7g3) (no related file):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Okay, ensure there is a Jira task to track this pending item.
</blockquote></details>

For point 4, this might help clarify things better.
"If you are a catalog author or an administrator, you can copy, move, delete, or rename catalog items that
were uploaded, imported, or captured to a catalog that your organization owns, whether or not the
catalog is published externally. Changes you make to an externally published catalog are replicated to
all of the catalog's subscribers when those subscribers synchronize their copy of the catalog."

"After you add vApp templates or media files to a catalog, you might need to modify the CatalogItem objects
that represent them. Your rights to manipulate catalog items depend on the source from which the catalog
items were created.
You cannot make changes to catalog items in catalogs that have an external subscription. "

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/utils.py, line 263 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L22ZZVo-PGVTxZsFRxC:-L22ZZVo-PGVTxZsFRxD:b-y1caeh) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/utils.py#L263)):*
> ```Python
>         access_str = access_str.strip("'")
>         access_setting = access_str.split(":")
>         access_dict = {'type': access_setting[0], 'name': access_setting[1]}
> ```

What happens if user specifies "    :   :    "
Raise an exception for all user errors. We should not let the burden of user errors to be handled by PyVcloud or vCD.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L2-dBD9M5-R3KHZ6_HI:brqeeyz) (no related file):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

same applies to `delete` instead of `remove`. For consistency we should use `delete`
</blockquote></details>

@Paco - In this case we are not creating the Access Control list, rather adding access control settings to the list. The list starts to exist as soon as the entity (viz. vapp, catalog, vdc etc.) is created. Think of it like adding a vm to an already existing vApp.

---

*[vcd_cli/catalog.py, line 405 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L2-e64E-LhaGusjb3wJ:-L2-e64E-LhaGusjb3wK:bwtrzxy) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L405)):*
> ```Python
>         vcd catalog acl add my-catalog 'org:TestOrg1:ReadOnly'  \\
>             'user:TestUser1:ReadOnly'
>             Add one or more acl to the specified catalog. access-list is
> ```

I think we are abusing the acronym acl, ACL stands for Access Control List, we are adding/removing access settings/access control rules to the list. We should cleanup the documentation accordingly

---

*[vcd_cli/catalog.py, line 446 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L2-es3ge4wxsLvYonNl:-L2-es3ge4wxsLvYonNm:b-df418l) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L446)):*
> ```Python
> @click.argument('access-list',
>                 nargs=-1,
>                 required=True,
> ```

Do we need to specify this explicitly? arguments are always required, correct?

---

*[vcd_cli/catalog.py, line 454 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L236l6HWCL7UxgmML-p:-L236l6HWCL7UxgmML-q:b-69eta0) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L454)):*
> ```Python
>         org = Org(client, in_use_org_href)
> 
>         updated_access = \
> ```

The formatting of this line looks weird, can you run yapf to format it ?

variable name -> updated_acl ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by anusuyar** [comment]
Adding required=True for access_list argument.

---

Review status: 0 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/catalog.py, line 446 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L2-es3ge4wxsLvYonNl:-L26xWf_gR3uw2yq6ANX:b-xmdm89) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L446)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Done. Removed it. Arguments are required by default. But we can make it optional by passing requred=False
</blockquote></details>

I just realized. I added required=True on purpose. we want access-list to be 1 or more. Without required=True, it becomes 0 or more. Reverting back the change.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-:-L26xMeJoVHUf8gYcyIo:bnpv9k5)*

**Comment by pacogomez** [comment]
Reviewed 2 of 2 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L26wRbacY5E19rtwO9f:bpne8rg) (no related file):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

> in general we use the verb create instead of add. For consistency we should use create here too.

Like aritra has mentioned. Its more about adding acl to an Entity. Rather than creating an acl. I think it should be add and remove
</blockquote></details>

ok, let's then use add/remove, please update the internal table that tracks the commands syntax

---

*[vcd_cli/catalog.py, line 446 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L2-es3ge4wxsLvYonNl:-L26xGmeHRXDBk2EMBVM:bkxzb1p) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L446)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I just realized. I added required=True on purpose. we want access-list to be 1 or more. Without required=True, it becomes 0 or more. Reverting back the change.
</blockquote></details>

if `metavar` is not defined, then the help will represent the fact that can be N items. I suggest removing this metavar param to use the default.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by anusuyar** [comment]
Review status: 1 of 2 files reviewed at latest revision, 7 unresolved discussions.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L1xIqXbSySywQZLHvvK:-L27-c07UVW70A7FbYDM:bq4m3rl) (no related file):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

ok, let's then use add/remove, please update the internal table that tracks the commands syntax
</blockquote></details>

@pacogomez I will update that doc.

---

*[vcd_cli/catalog.py, line 446 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L2-es3ge4wxsLvYonNl:-L27-kVMbV2Aihzh8K1G:bvfrqte) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L446)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

if `metavar` is not defined, then the help will represent the fact that can be N items. I suggest removing this metavar param to use the default.
</blockquote></details>

Done. Removed metavar for access-list arg in both add and remove command.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-:-L270CvHOKcJNZpP21ez:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 2 files at r2, 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/catalog.py, line 446 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-L2-es3ge4wxsLvYonNl:-L26vMM_SVcRyUY-bV4P:b7xs621) ([raw file](https://github.com/vmware/vcd-cli/blob/07327aaaad51fa4b51cf6caf271d9bf189a19802/vcd_cli/catalog.py#L446)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Done. Removed it. Arguments are required by default. But we can make it optional by passing requred=False
</blockquote></details>

Access-list should have atleast one access-setting. Please mark Required=True

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/153#-:-L27MCDJQeMKNpDCN5bL:bnfp4nl)*

**Pull request merged**
