### PR TITLE
VCDA-417: commands to manage extension commands

### PR DESCRIPTION
**Pull request by pacogomez**
- added list/add/remove extension commands, under the profile sub-command
- added warning when a module with extension commands can't be loaded
- added profile info command

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/187)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/profile.py, line 86 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4l2YqGdkUJappJCd73:-L4l2YqH7jLL3CP9ie93:bq85l2n) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L86)):*
> ```Python
>                 profiles.data['extensions'] is not None:
>             for extension in profiles.data['extensions']:
>                 click.echo(extension)
> ```

When do we use click.echo vs stdout?

---

*[vcd_cli/profile.py, line 101 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4l3HBtiTc87oWvt-EN:-L4l3HBtiTc87oWvt-EO:b-uwr7mt) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L101)):*
> ```Python
>             profiles.data['extensions'] = []
>         if module not in profiles.data['extensions']:
>             profiles.data['extensions'].append(module)
> ```

How do we validate whether user entered correct extension name?

This lets user add anything and fail at later commands. Should we provide user an option to choose one of the valid extensions via Click? What do you think?

---

*[vcd_cli/profile.py, line 103 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4l2e0FdhlsSgWsjUdJ:-L4l2e0FdhlsSgWsjUdK:bfpmvpm) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L103)):*
> ```Python
>             profiles.data['extensions'].append(module)
>             profiles.save()
>             click.secho('Extension added from module \'%s\'.' % module)
> ```

why not stdout?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187)*

**Comment by sahithi** [comment]
If it is a quick task, we can include a command to set the location for vcd.log.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-:-L4l79zUhjoKw0Xoj5W8:b-ev1e17)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/plugin.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4lKNqGa-GZClmwjHpD:-L4lKNqGa-GZClmwjHpE:b-m68z93) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L23)):*
> ```Python
>     profiles = Profiles.load()
>     if 'extensions' in profiles.data and \
>             profiles.data['extensions'] is not None:
> ```

How would I be able to tell that the load failed in a script?  Do you mean eat the exception without generating a return code?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187)*

**Comment by pacogomez** [comment]
it will take some design and refactoring effort, I prefer to leave it for another task. I believe there is a lira story already created.

---

Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vcd_cli/plugin.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4lKNqGa-GZClmwjHpD:-L4mmADQ_-b39QRA9z-z:b-llbyd8) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L23)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

How would I be able to tell that the load failed in a script?  Do you mean eat the exception without generating a return code?
</blockquote></details>

if the script calls a command that failed to load, it will fail with a 'no such command' error message and a non zero exit code

---

*[vcd_cli/profile.py, line 86 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4l2YqGdkUJappJCd73:-L4mmriuLQfluNX0kAGQ:b6ihxnr) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L86)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

When do we use click.echo vs stdout?
</blockquote></details>

there are some advantages of using `click.echo` http://click.pocoo.org/6/utils/#printing-to-stdout and that's we use it across all `vcd-cli`

---

*[vcd_cli/profile.py, line 101 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4l3HBtiTc87oWvt-EN:-L4mn7ZTHonnE3AG6JSR:b-b0v3yb) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L101)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

How do we validate whether user entered correct extension name?

This lets user add anything and fail at later commands. Should we provide user an option to choose one of the valid extensions via Click? What do you think?
</blockquote></details>

the extension is loaded dynamically every time vcd-cli starts, so validating it here during installation doesn't make much difference if later the environment changes, for example, the python module that contains the extension is removed.

---

*[vcd_cli/profile.py, line 103 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4l2e0FdhlsSgWsjUdJ:-L4mncu_keH7a4nXwZ5w:b-ftfv98) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L103)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

why not stdout?
</blockquote></details>

echo or secho is preferred for the reasons in the link above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-:-L4mlvQj5byfxiSZDHBt:begvx48)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions, some commit checks failed.

---

*[vcd_cli/plugin.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4lKNqGa-GZClmwjHpD:-L4mnuQuPE0Fhhm3wmEq:b-s17yih) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L23)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

if the script calls a command that failed to load, it will fail with a 'no such command' error message and a non zero exit code
</blockquote></details>

this is done this way so even if the extension is incorrect or not loaded properly, vcd-cli still is functional and user is able to fix the error in the registration

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-:-L4mpnXBYKsX3Jk1bkUc:bnfp4nl)*

**Comment by anusuyar** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[vcd_cli/plugin.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4lKNqGa-GZClmwjHpD:-L4mkC4o7w4g4wkC4xmQ:blnkqbb) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L23)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

How would I be able to tell that the load failed in a script?  Do you mean eat the exception without generating a return code?
</blockquote></details>

I think we need to propagate the exception in Profile.load() to the calling methods. For some reason, if we cannot open the profile.yaml file, the user should get an appropriate exception to deal with the failure

---

*[vcd_cli/plugin.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4mm0kAU196yMKLnF2G:-L4mm0kAU196yMKLnF2H:bu1do68) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L27)):*
> ```Python
>             try:
>                 __import__(extension)
>             except Exception:
> ```

if we don't eat up the exception in Profiles.load(), we can catch specific exceptions and show the appropriate message to the user. Something similar to following

```
def load_user_plugins():

    try:
        profiles = Profiles.load()
        if 'extensions' in profiles.data and \
                profiles.data['extensions'] is not None:
            for extension in profiles.data['extensions']:
        __import__(extension)
    except(IOError, OSError):
        click.echo('Could not open the profiles.yaml file')
    except ImportError:
        click.echo('Could not import extentions')
    except Exception:
         click.echo('Could not load extentions')
```

This can help users know why specifically the command is failing.

---

*[vcd_cli/profile.py, line 87 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4mrfFjpWqLzqUGjjdb:-L4mrfFjpWqLzqUGjjdc:b-p1n3an) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L87)):*
> ```Python
>             for extension in profiles.data['extensions']:
>                 click.echo(extension)
>     except Exception as e:
> ```

Same comment for exception handling as  in 'line 27'

---

*[vcd_cli/profile.py, line 106 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4ms49nawMosTdj43Fv:-L4ms49nawMosTdj43Fw:b-p1n3an) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L106)):*
> ```Python
>         else:
>             raise Exception('module already in the profile')
>     except Exception as e:
> ```

Same comment for exception handling as  in 'line 27'

---

*[vcd_cli/profile.py, line 126 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4ms7Dk6VNUtRuOvr6P:-L4ms7Dk6VNUtRuOvr6Q:b-p1n3an) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L126)):*
> ```Python
>         profiles.save()
>         click.secho('Extension from module \'%s\' deleted.' % module)
>     except Exception as e:
> ```

Same comment for exception handling as  in 'line 27'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187)*

**Comment by pacogomez** [comment]
Review status: 2 of 4 files reviewed at latest revision, 8 unresolved discussions, some commit checks failed.

---

*[vcd_cli/plugin.py, line 23 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4lKNqGa-GZClmwjHpD:-L4nGsnYixNu-DUDil6B:b-c7yrq7) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L23)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think we need to propagate the exception in Profile.load() to the calling methods. For some reason, if we cannot open the profile.yaml file, the user should get an appropriate exception to deal with the failure
</blockquote></details>

I added another except branch and I added exception handling inside Profiles.load()

---

*[vcd_cli/plugin.py, line 27 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4mm0kAU196yMKLnF2G:-L4ncLjxo-uwHSefcUiw:bun20qm) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/plugin.py#L27)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

if we don't eat up the exception in Profiles.load(), we can catch specific exceptions and show the appropriate message to the user. Something similar to following

```
def load_user_plugins():

    try:
        profiles = Profiles.load()
        if 'extensions' in profiles.data and \
                profiles.data['extensions'] is not None:
            for extension in profiles.data['extensions']:
        __import__(extension)
    except(IOError, OSError):
        click.echo('Could not open the profiles.yaml file')
    except ImportError:
        click.echo('Could not import extentions')
    except Exception:
         click.echo('Could not load extentions')
```

This can help users know why specifically the command is failing.
</blockquote></details>

I added exception handling in Profiles.load()

---

*[vcd_cli/profile.py, line 87 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4mrfFjpWqLzqUGjjdb:-L4ncU_UJNsB5QCpOSJR:bun20qm) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L87)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Same comment for exception handling as  in 'line 27'
</blockquote></details>

I added exception handling in Profiles.load()

---

*[vcd_cli/profile.py, line 106 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4ms49nawMosTdj43Fv:-L4ncVb78-w8c911H1ay:bun20qm) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L106)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Same comment for exception handling as  in 'line 27'
</blockquote></details>

I added exception handling in Profiles.load()

---

*[vcd_cli/profile.py, line 126 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-L4ms7Dk6VNUtRuOvr6P:-L4ncXHPeZCIv-DqpLay:bun20qm) ([raw file](https://github.com/vmware/vcd-cli/blob/2ad9a351c8df00034885bb99984070da0dd7544e/vcd_cli/profile.py#L126)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Same comment for exception handling as  in 'line 27'
</blockquote></details>

I added exception handling in Profiles.load()

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-:-L4rCG3vBJbUQKOXiL5E:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187#-:-L4rCgqTOB5mCE3LvCLo:bnfp4nl)*

**Comment by hodgesrm** [comment]
Reviewed 1 of 3 files at r1, 3 of 4 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/187)*

**Pull request merged**
