### PR TITLE
VCDA-229 & VCDA-455: Show Info of Right and Role

### PR DESCRIPTION
**Pull request by sahithi**
1. Command to show Info on a given Role
2. Command to show Info on a given Right
3. Renamed method org.get_right() ->org.get_right_record() & org.get_role() -> org.get_role_record()

Command Ouput:
> vcd role info 'vApp User'
>
>property     value
>-----------  --------------------------------------------------------------------------
>Description  Rights given to a user who uses vApps created by others
>href         https://127.0.0.1:8443/api/admin/role/d184a8ff-68b1-4bf2-ad26-06e208c1f93f
>id           d184a8ff-68b1-4bf2-ad26-06e208c1f93f
>name         vApp User
>type         application/vnd.vmware.admin.role+xml

> vcd right info 'vCenter: View'
>
>property          value
>----------------  ------------------------------------
>BundleKey         RIGHT_VCENTER_VIEW
>Category          vCenter
>Description       vCenter: View
>ServiceNamespace  com.vmware.vcloud
>id                96a8412f-ba73-3ad1-a20b-4d5bbb09c215
>name              vCenter: View

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/166)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 0 of 3 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/166#-:-L3B6yxwqMFx_97pm5e-:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/166#-:-L3F2oUxteZ4bdgKm1KV:bnfp4nl)*

**Comment by sompa** [comment]
*[vcd_cli/role.py, line 117 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/166#-L3FE-0gAI9HUuLnDyql:-L3FE-0gAI9HUuLnDyqm:bptt0y5) ([raw file](https://github.com/vmware/vcd-cli/blob/c9e2b471682a7814718388d466c93b2a04b57ee5/vcd_cli/role.py#L117)):*
>         stdout(to_dict(role_resource, exclude=['Link', 'RightReferences']), ctx)
Line length >80 . Run flake8 tests to ensure its correct.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/166)*

**Comment by sompa** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/166)*

**Pull request merged**
