### PR TITLE
VCDA-354: CSE support multiple vCenters

### PR DESCRIPTION
**Pull request by pacogomez**
- refactored Extension to APIExtension
- improved stdout
- added new commands vc to list vCenters and get vCenter info
- renamed list vms to avoid use of reserved word

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/163)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/vcd.py, line 131 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/163#-L30N8vbVVMeQSfBgVFc:-L30N8vcrDNBoWxjMbTt:botwksz) ([raw file](https://github.com/vmware/vcd-cli/blob/1fe3825cf7bb98c8705d5f99ce14645f532f49e1/vcd_cli/vcd.py#L131)):*
> ```Python
>     from vcd_cli import search  # NOQA
>     from vcd_cli import system  # NOQA
>     from vcd_cli import task  # NOQA
> ```

What does NOQA mean? Thanks!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/163)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks pending.

---

*[vcd_cli/vcd.py, line 131 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/163#-L30N8vbVVMeQSfBgVFc:-L30Sm0Gf02CiqFv2zb-:bc9xwmh) ([raw file](https://github.com/vmware/vcd-cli/blob/1fe3825cf7bb98c8705d5f99ce14645f532f49e1/vcd_cli/vcd.py#L131)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

What does NOQA mean? Thanks!
</blockquote></details>

it skips flake8 style validation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/163)*

**Comment by sahithi** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vcd_cli/vc.py, line 50 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/163#-L323mLuHqYUKXEash3F:-L323mLvo6snCUC7ORGu:b-3w70x3) ([raw file](https://github.com/vmware/vcd-cli/blob/1fe3825cf7bb98c8705d5f99ce14645f532f49e1/vcd_cli/vc.py#L50)):*
> ```Python
> def list_vcenters(ctx):
>     try:
>         platform = Platform(ctx.obj['client'])
> ```

Any reason why you chose 'Platform' as a name?
Why can't we put these methods list_vcenters().. in System.py?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/163)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks broke.

---

*[vcd_cli/vc.py, line 50 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/163#-L323mLuHqYUKXEash3F:-L33CZGip30X4lkQ1g7B:biey7an) ([raw file](https://github.com/vmware/vcd-cli/blob/1fe3825cf7bb98c8705d5f99ce14645f532f49e1/vcd_cli/vc.py#L50)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Any reason why you chose 'Platform' as a name?
Why can't we put these methods list_vcenters().. in System.py?
</blockquote></details>

System originally refers to the System organization. Platform has been created to work with the vSphere resources of the underlying platform, which might not be associated to any organization.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/163)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/163#-:-L34MrZsK28Uunb-gZvi:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 5 of 5 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved, some commit checks broke.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/163)*

**Pull request merged**
