### PR TITLE
Updated requirements with version info

### PR DESCRIPTION
**Pull request by pacogomez**
- updated requirements with version info
- sorted dependencies alphabetically
- removed public IP addresses from sample files

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/178)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Review status: 0 of 7 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/178#-L3jlIEeekiGvVq6YVGo:-L3jlIEfyrPF_yCz9ubo:b-ceqj49) (no related file):*
Can you add a README.md to explain what these files do?  (Comments in the files would be fine as well.)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/178)*

**Comment by pacogomez** [comment]
Review status: 0 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/178#-L3jlIEeekiGvVq6YVGo:-L3jtRJL5l1BW_G3XEOn:bb3n5g3) (no related file):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Can you add a README.md to explain what these files do?  (Comments in the files would be fine as well.)
</blockquote></details>

added README

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/178)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 8 of 8 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/178#-:-L3jujjJ2xH_kzPyB557:bnfp4nl)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 7 of 26 files reviewed at latest revision, 1 unresolved discussion.

---

*[a discussion](https://reviewable.io:443/reviews/vmware/vcd-cli/178#-L3jlIEeekiGvVq6YVGo:-L3k9bWFo-2yEHSyJgeB:bvtka37) (no related file):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

added README
</blockquote></details>

Thanks!!!

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/178#-:-L3k9fa1ljohkwpUQTAs:bnfp4nl)*

**Pull request merged**
