### PR TITLE
 VCDA-311 : Unifying argument 'name' and option 'id' for independent disk related commands

### PR DESCRIPTION
**Pull request by rocknes**
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd disk list
id                                    name    owner      size        size_bytes  status    vms_attached
------------------------------------  ------  ---------  --------  ------------  --------  --------------
bea35db5-7c44-4d52-bbfd-1126162b8b50  disk1   org-admin  20 bytes            20  Resolved
efa4f7ea-62ba-415c-9427-c2a7d96a5ed3  disk1   org-admin  10 bytes            10  Resolved

(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd disk info disk1
Usage: vcd disk info [OPTIONS] <name>

Error: Found multiple disks with name disk1, please identify disk via disk-id.

(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd disk info id:bea35db5-7c44-4d52-bbfd-1126162b8b50
property        value
--------------  ------------------------------------
busSubType      lsilogic
busType         6
description     second disk
id              bea35db5-7c44-4d52-bbfd-1126162b8b50
iops            0
name            disk1
owner           org-admin
size            20 bytes
size_bytes      20
status          1
storageProfile  *

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/158)

### CODE REVIEW

**Comment by pacogomez** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/disk.py, line 254 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L27wQYeVXBT4aD8RwZl:-L27wQYeVXBT4aD8RwZm:bnyv8bv) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L254)):*
> ```Python
> 
>         disk_id = None
>         if disk_name.startswith('uuid:'):
> ```

I would make it case insensitive

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/disk.py, line 254 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L27wQYeVXBT4aD8RwZl:-L2GFBA4fDZydizfprsR:badhfxm) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L254)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I would make it case insensitive
</blockquote></details>

Yup, will change to disk_name.lower().startswith('uuid:')
Waiting for review comments for others, want to minimize number of commits addressing review comments :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/disk.py, line 254 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L27wQYeVXBT4aD8RwZl:-L2GFkCppxq8SYF0uAF2:bnx9ic) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L254)):*
> Waiting for review comments for others
Waiting for review comments *from* others

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by pacogomez** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/disk.py, line 254 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L27wQYeVXBT4aD8RwZl:-L2IZKBWNScLZ1dgXFVR:b-pslrhf) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L254)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

> Waiting for review comments for others
Waiting for review comments *from* others
</blockquote></details>

also, through vCD REST API, the id field name is `id`, even if it uses an `UUID` formatted string. Maybe we should use `id:` or `ID:` as the prefix instead of `uuid:`

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/disk.py, line 254 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L27wQYeVXBT4aD8RwZl:-L2Inmk1oMMeaZs9JT7W:b37ln7k) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L254)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

also, through vCD REST API, the id field name is `id`, even if it uses an `UUID` formatted string. Maybe we should use `id:` or `ID:` as the prefix instead of `uuid:`
</blockquote></details>

Sounds good, will change to 'id'

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by anusuyar** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/disk.py, line 186 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mya_9kUWQO5uYWTwo:-L2Mya_9kUWQO5uYWTwp:b-7hcjrk) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L186)):*
> ```Python
>               'new_name',
>               required=False,
>               metavar='<new name>',
> ```

should this be <new-name >?

---

*[vcd_cli/disk.py, line 204 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mz-ngKv9V_8sJiGZP:-L2Mz-nheBClnTMqBGwU:b-ybtrgy) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L204)):*
> ```Python
>               'storage_profile',
>               required=False,
>               metavar='<storage profile name>',
> ```

We are following a pattern for metavar as something like this storage-profile right? We have help to describe the name in detail. I don't think we need to be detailed for metavar

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/disk.py, line 186 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mya_9kUWQO5uYWTwo:-L2NBu-I8o2khzICsm1s:b-fk92p2) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L186)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

should this be <new-name >?
</blockquote></details>

wwill change to just <name>

---

*[vcd_cli/disk.py, line 204 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mz-ngKv9V_8sJiGZP:-L2NBooBuBxCL4sTZCnr:b-y7xe1p) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L204)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

We are following a pattern for metavar as something like this storage-profile right? We have help to describe the name in detail. I don't think we need to be detailed for metavar
</blockquote></details>

Yeah, I agree, will change metavar to just <name>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/disk.py, line 186 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mya_9kUWQO5uYWTwo:-L2NBymFL20F3Fb0pspT:b-1jcke9) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L186)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

wwill change to just <name>
</blockquote></details>

Aggrh. \< are not escaped :(
I meant \<name\>

---

*[vcd_cli/disk.py, line 204 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mz-ngKv9V_8sJiGZP:-L2NC2a9gPuU5YqYYXKr:b-1jcke9) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L204)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Yeah, I agree, will change metavar to just <name>
</blockquote></details>

Aggrh. \< are not escaped :(
I meant \<name\>

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/disk.py, line 75 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2NGEvEa-YZfaMyMAtn:-L2NGEvEa-YZfaMyMAto:b-shfxi6) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L75)):*
>  disk_id = None
>         if name.startswith('uuid:'):
>             disk_id = name[5:]

I see above code duplicated at several places. Can we move this to a new utils method?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/disk.py, line 75 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2NGEvEa-YZfaMyMAtn:-L2NKcEJuzVfo6VAsOWn:b-dk9rrn) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L75)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

>  disk_id = None
>         if name.startswith('uuid:'):
>             disk_id = name[5:]

I see above code duplicated at several places. Can we move this to a new utils method?
</blockquote></details>

Moving the logic into a file level utility function.
This functionality is being used by just four of the functions in disk.py, moving it to utils.py doesn't seem to be useful.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/disk.py, line 75 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2NGEvEa-YZfaMyMAtn:-L2NM6vfthPoXm_uW0dj:bnc7bux) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L75)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Moving the logic into a file level utility function.
This functionality is being used by just four of the functions in disk.py, moving it to utils.py doesn't seem to be useful.
</blockquote></details>

On a second thought two functions in vapp.py are also using this functionality. Will move the function to utils.py.
p.s. I am still little hesitant to put this function in utils.py since the usage is so narrow.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by pacogomez** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/disk.py, line 75 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2NGEvEa-YZfaMyMAtn:-L2Od4nzRdIIuZlNdaxe:blvb8ig) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L75)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

On a second thought two functions in vapp.py are also using this functionality. Will move the function to utils.py.
p.s. I am still little hesitant to put this function in utils.py since the usage is so narrow.
</blockquote></details>

if more than one module use it, moving it to utils.py is fine

---

*[vcd_cli/disk.py, line 204 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mz-ngKv9V_8sJiGZP:-L2Oep5J8O3rOYftBfaH:b-2r2ktd) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L204)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Aggrh. \< are not escaped :(
I meant \<name\>
</blockquote></details>

we should discuss in general how we use `metavar`: use the default or what conventions we want to use consistently

---

*[vcd_cli/disk.py, line 34 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OgSQbBun5xJpuuxYI:-L2OgSQbBun5xJpuuxYJ:bettk7s) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/disk.py#L34)):*
> ```Python
> def disk(ctx):
>     """Manage independent disks in vCloud Director.
> ```

a brief note about using disk names and ids, could be useful to the user

---

*[vcd_cli/utils.py, line 323 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OfTnEd-YVvvUunDfP:-L2OfTnEd-YVvvUunDfQ:bn71aps) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/utils.py#L323)):*
> ```Python
> 
> 
> def convert_disk_name_user_input_to_name_and_id(str):
> ```

`extract_name_or_id` is also descriptive and shorter, but this is subjective

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/disk.py, line 204 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2Mz-ngKv9V_8sJiGZP:-L2PH5SNXZ2Ghn60V6yP:b-9d742d) ([raw file](https://github.com/vmware/vcd-cli/blob/481b8f53fde3640e5ecff5d1618de388480bbbb3/vcd_cli/disk.py#L204)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

we should discuss in general how we use `metavar`: use the default or what conventions we want to use consistently
</blockquote></details>

Yes, I agree on that, there is major inconsistency in the way we are using metavar across the project. 

---

*[vcd_cli/disk.py, line 34 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OgSQbBun5xJpuuxYI:-L2PHzCZU2hM2_SVCc3o:b-vdat5f) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/disk.py#L34)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

a brief note about using disk names and ids, could be useful to the user
</blockquote></details>

Will update the section with relevant details.

---

*[vcd_cli/utils.py, line 323 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OfTnEd-YVvvUunDfP:-L2PHHkCfO0lBANkSbzl:b-sjgvxc) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/utils.py#L323)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

`extract_name_or_id` is also descriptive and shorter, but this is subjective
</blockquote></details>

The reason I was hesitant to move this function in utils.py is because the function is very specialized and the name of the function needs to be very descriptive, which makes it a rather long and ugly function name.

However I would prefer to keep the long name.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/utils.py, line 323 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OfTnEd-YVvvUunDfP:-L2QNNbnROqz4HHEsxtl:b-of7o73) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/utils.py#L323)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The reason I was hesitant to move this function in utils.py is because the function is very specialized and the name of the function needs to be very descriptive, which makes it a rather long and ugly function name.

However I would prefer to keep the long name.
</blockquote></details>

the name might have about the same number of characters than the implementation, but names don't break logic so I'm ok with that :)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-:-L2QNkITN-ubrgjS-cdO:bnfp4nl)*

**Comment by sompa** [comment]
*[vcd_cli/disk.py, line 49 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2RIB10HVEe62j-d7Io:-L2RIB10HVEe62j-d7Ip:b925u8u) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/disk.py#L49)):*
> ```Python
>             Get details of the disk for a given id.
> \b
>         vcd disk update disk1 --size 20g --description "new description"
> ```

what does the size '20g' mean ? 20 gigabytes ? Don't we specify disk size in bytes/kb while creating and updating the independent disk ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by sompa** [comment]
Reviewed 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/disk.py, line 49 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2RIB10HVEe62j-d7Io:-L2RdB5i2NcrWlzSHlXa:b-goiiy5) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/disk.py#L49)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

what does the size '20g' mean ? 20 gigabytes ? Don't we specify disk size in bytes/kb while creating and updating the independent disk ?
</blockquote></details>

The param is expecting size in bytes, but we have introduced a middle layer of humanfriendly parsing, which allows users to enter 'human-friendly' numbers like 20g which is 20 gigs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by anusuyar** [comment]
Reviewed 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/utils.py, line 323 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OfTnEd-YVvvUunDfP:-L2Rg4QZxsm5CUQ0LE12:bhb2zf3) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/utils.py#L323)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

the name might have about the same number of characters than the implementation, but names don't break logic so I'm ok with that :)
</blockquote></details>

I don't think we need such a long method name.  It looks very odd. We don't need to explain the entire logic of the method in the method name.  

Something like below looks better.
extract_name_or_id(disk_input_str)  
"""Explain the what exactly the method does in the doc string. Also about what disk_input_str in the arg really mean.

"""

Also, since we are returning 2 return values. We need to document what each return value signifies. first return val is disk_id, next one is disk_name

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by rocknes** [comment]
Review status: 0 of 3 files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/utils.py, line 323 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-L2OfTnEd-YVvvUunDfP:-L2RuM2M286EPPhA1SM3:biae2tk) ([raw file](https://github.com/vmware/vcd-cli/blob/3002dc0b5105363b7b286182d097fc61d69c9fc9/vcd_cli/utils.py#L323)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I don't think we need such a long method name.  It looks very odd. We don't need to explain the entire logic of the method in the method name.  

Something like below looks better.
extract_name_or_id(disk_input_str)  
"""Explain the what exactly the method does in the doc string. Also about what disk_input_str in the arg really mean.

"""

Also, since we are returning 2 return values. We need to document what each return value signifies. first return val is disk_id, next one is disk_name
</blockquote></details>

Updated the code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 3 of 3 files at r4.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/158#-:-L2RuqFsLpZzYzMZzmJO:bnfp4nl)*

**Pull request merged**
