### PR TITLE
Link/Unlink role to its template

### PR DESCRIPTION
**Pull request by sahithi**
1. [New] Commands to link and unlink role from its template.
2. [Fixes] Refactor existing commands to use org_in_use href instead of retrieving the resource by name.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/154)

### CODE REVIEW

**Comment by anusuyar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/role.py, line 39 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L1xycawv_nCtwAkLMFO:-L1xycawv_nCtwAkLMFP:b-o4fgnn) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L39)):*
> ```Python
> \b
>         vcd role link myRole -o myOrg
>             Links the role to it's original template.
> ```

What do we mean by template here? It is not clear to me by looking at the description

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by sompa** [comment]
*[vcd_cli/role.py, line 43 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L1yMYX9q3SF1Z65DFq1:-L1yMYX9q3SF1Z65DFq2:b-amajy0) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L43)):*
> ```Python
>         vcd role unlink myRole -o myOrg
>             Unlinks the role from its template.
>     """
> ```

Could we be more subtle about the example template names we are using in the doc ? To me it looks like this is to link a role to an organization rather than a role template in an org.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by sompa** [comment]
*[vcd_cli/role.py, line 167 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L1yN29mrxmIQGB_pIZT:-L1yN29mrxmIQGB_pIZU:b-dvrlm1) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L167)):*
> ```Python
>         stderr(e, ctx)
> 
> @role.command('unlink', short_help='Unlink the role of a given org from its template')
> ```

Could you run flake8 for this ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by sompa** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 39 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L1xycawv_nCtwAkLMFO:-L1y_6lTtK8NBJFUFcqR:bbv6l3c) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L39)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

What do we mean by template here? It is not clear to me by looking at the description
</blockquote></details>

Please refer this documentation 
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/00ee5584-4b56-4f84-8d98-96e159f19d59/27ffcd9e-1800-405a-b859-be3ed0d693ed/doc/GUID-7D7D04B9-A002-4C87-ABF9-FC35B9026AAD.html#GUID-7D7D04B9-A002-4C87-ABF9-FC35B9026AAD

Admins are expected to know what a role template is to execute this command and they can refer to the documentation. (Need to explain what a role template here is = the need to explain what a vApp template is (or) what an orgVdc is)

---

*[vcd_cli/role.py, line 43 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L1yMYX9q3SF1Z65DFq1:-L1yaNaYk9LQ9sizLN_z:b-3w7rmo) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L43)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Could we be more subtle about the example template names we are using in the doc ? To me it looks like this is to link a role to an organization rather than a role template in an org.
</blockquote></details>

Please refer this documentation 
https://vdc-repo.vmware.com/vmwb-repository/dcr-public/00ee5584-4b56-4f84-8d98-96e159f19d59/27ffcd9e-1800-405a-b859-be3ed0d693ed/doc/GUID-7D7D04B9-A002-4C87-ABF9-FC35B9026AAD.html#GUID-7D7D04B9-A002-4C87-ABF9-FC35B9026AAD

There is no need to specify template names.
-o myOrg ( explanation for this is given at the basic description of roles).

---

*[vcd_cli/role.py, line 167 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L1yN29mrxmIQGB_pIZT:-L1ybMmbRrwe_QN8fsdQ:bqqdqs5) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L167)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Could you run flake8 for this ?
</blockquote></details>

No warnings or errors.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-:-L1ydZ4XRJ_eVeyezrJV:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 71 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L20NDE4r5fv00KR0der:-L20NDE4r5fv00KR0des:b-cxggl1) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L71)):*
> ```Python
>         roles = org.list_roles()
>         for role in roles:
>             del role['href']
> ```

`href` attribute should be displayed if the output type is xml, json or yaml. It should not be removed. See `Catalog.list_catalogs_or_items` and `VApp.list_vapps` for examples. `to_dict` can be used with the default `exclude` param.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 71 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L20NDE4r5fv00KR0der:-L222wLqwCr-QvtkE0pY:bssoz3f) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L71)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

`href` attribute should be displayed if the output type is xml, json or yaml. It should not be removed. See `Catalog.list_catalogs_or_items` and `VApp.list_vapps` for examples. `to_dict` can be used with the default `exclude` param.
</blockquote></details>

Discussed with Paco offline and leaving as-is for now.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 71 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-L20NDE4r5fv00KR0der:-L229wz1zVUU0b2kvnF_:b32w0x) ([raw file](https://github.com/vmware/vcd-cli/blob/7500d94c71407f9e44042fffd129ea6995a68fd6/vcd_cli/role.py#L71)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Discussed with Paco offline and leaving as-is for now.
</blockquote></details>

OK

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/154#-:-L22A1QZItvcldq9TOhG:bnfp4nl)*

**Pull request merged**
