### PR TITLE
VCDA-473: Implement vcd user list command

### PR DESCRIPTION
**Pull request by anusuyar**
C:\sources\github\service_ecosystem\vcd-cli (master)
(vcd-cli) λ vcd user list -o AnuOrg
  deployedVMQuota    deployedVMQuotaRank  fullName    identityProviderType    isEnabled    isLdapUser    name        numberOfDeployedVMs    numberOfStoredVMs    storedVMQuota    storedVMQuotaRank
-----------------  ---------------------  ----------  ----------------------  -----------  ------------  --------  ---------------------  -------------------  ---------------  -------------------
                0                     -1              INTEGRATED              true         false         user1                         0                    0                0                   -1
                0                     -1              INTEGRATED              true         false         user2                         0                    0                0                   -1
                0                     -1              INTEGRATED              true         false         vappuser                      0                    2                0                   -1
                0                     -1              INTEGRATED              true         false         user                          0                    2                0                   -1

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/179)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-:-L3kGwTgG3pp6lVT0vPs:bnfp4nl)*

**Comment by sahithi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179)*

**Comment by anusuyar** [comment]
Moved to_dict to vcd-cli

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-:-L3oRY725ZyfbqzQDKeh:b-wsnk2r)*

**Comment by sahithi** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/user.py, line 261 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-L3otBbvyexcM1nWIWk4:-L3otBbws3-xJ2_l8m2b:bivcp1u) ([raw file](https://github.com/vmware/vcd-cli/blob/feb2b541149765c3bac74e35a8d66eb520219ad4/vcd_cli/user.py#L261)):*
> ```Python
>         users = org.list_users()
>         result = []
>         for record in list(users):
> ```

Any specific need for wrapping it in list(users)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/user.py, line 261 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-L3otBbvyexcM1nWIWk4:-L3oueI-u_lcWXzrjmVp:b-4ewua0) ([raw file](https://github.com/vmware/vcd-cli/blob/feb2b541149765c3bac74e35a8d66eb520219ad4/vcd_cli/user.py#L261)):*
> list_users
list_users returns query.execute(). we need to convert the query result to iterate the users

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179)*

**Comment by pacogomez** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/user.py, line 261 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-L3otBbvyexcM1nWIWk4:-L3ox4q_D2WLs4KwlOEB:b-x9nhx6) ([raw file](https://github.com/vmware/vcd-cli/blob/feb2b541149765c3bac74e35a8d66eb520219ad4/vcd_cli/user.py#L261)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

> list_users
list_users returns query.execute(). we need to convert the query result to iterate the users
</blockquote></details>

I suggest removing `deployedVMQuotaRank` and `storedVMQuotaRank` from the list to make it less wide. Those fields can be displayed in a `vcd user info <user_id>` command

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-:-L3ozNtuq_udRRJxl1Yi:bnfp4nl)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/179#-:-L3p6Gs1Yj-NzRn9B5qP:bnfp4nl)*

**Pull request merged**
