### PR TITLE
[vcd-cli] delete role from a given org

### PR DESCRIPTION
**Pull request by sahithi**
> vcd role delete demoRole
Role 'demoRole' has been successfully deleted.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/146)

### CODE REVIEW

**Comment by anusuyar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/role.py, line 121 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/146#-L0k_KDjVn3wQDxnwwIS:-L0k_KDjVn3wQDxnwwIT:b-wqxpft) ([raw file](https://github.com/vmware/vcd-cli/blob/992740edaecb342fbaad538699fb274e1d6a6169/vcd_cli/role.py#L121)):*
> ```Python
>               help='name of the org',
>               )
> def delete(ctx, role_name, org_name):
> ```

We need to have a prompt asking the user if he wants to delete the role from this particular ORG.   This will aslo alert the users when the current org in use is org1 . but he wants to delete role in org2 but forgets to provide the org name. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/role.py, line 121 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/146#-L0k_KDjVn3wQDxnwwIS:-L0lbJVPsyRScOgArs6l:b-2lp1kw) ([raw file](https://github.com/vmware/vcd-cli/blob/992740edaecb342fbaad538699fb274e1d6a6169/vcd_cli/role.py#L121)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

We need to have a prompt asking the user if he wants to delete the role from this particular ORG.   This will aslo alert the users when the current org in use is org1 . but he wants to delete role in org2 but forgets to provide the org name. 
</blockquote></details>

all delete commands should have a confirmation flag (`--yes`). I think the top command help should provide a short note on what the precedence is: `--org` has preference over `current org`. Please provide a short description at the `vcd role`  command level. See `vcd login` and `vcd vapp` for examples

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146)*

**Comment by sahithi** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vcd_cli/role.py, line 121 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/146#-L0k_KDjVn3wQDxnwwIS:-L14SxKNAd5tjiCOpM43:b-bl05n4) ([raw file](https://github.com/vmware/vcd-cli/blob/992740edaecb342fbaad538699fb274e1d6a6169/vcd_cli/role.py#L121)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

all delete commands should have a confirmation flag (`--yes`). I think the top command help should provide a short note on what the precedence is: `--org` has preference over `current org`. Please provide a short description at the `vcd role`  command level. See `vcd login` and `vcd vapp` for examples
</blockquote></details>


@pacogomez I added little more to the already provided description.

@anusuyar Added force prompt reminding user about the current org context for now as there is no harm and as it is an added check.

All our existing CRUD commands are designed to execute in the context of current org-in-use if --org is not specified. I am not very sure if this force prompt is very required. Please bring this topic in the next design discussion if we need refactoring of the existing code to enforce the same.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146)*

**Comment by pacogomez** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vcd_cli/role.py, line 121 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/146#-L0k_KDjVn3wQDxnwwIS:-L1JEhf6dUydJGFYsNZL:b3i7368) ([raw file](https://github.com/vmware/vcd-cli/blob/992740edaecb342fbaad538699fb274e1d6a6169/vcd_cli/role.py#L121)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>


@pacogomez I added little more to the already provided description.

@anusuyar Added force prompt reminding user about the current org context for now as there is no harm and as it is an added check.

All our existing CRUD commands are designed to execute in the context of current org-in-use if --org is not specified. I am not very sure if this force prompt is very required. Please bring this topic in the next design discussion if we need refactoring of the existing code to enforce the same.
</blockquote></details>

There is already a pattern to confirm delete that is based on the `abort_if_false` callback that avoids writing custom code, please refer to other `delete` commands to provide a similar implementation

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146)*

**Comment by pacogomez** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146#-:-L1JYJyQPrtBMk2DDaBm:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/146#-:-L1JZ0uWdr-H1RZ-ZWNt:bnfp4nl)*

**Pull request merged**
