### PR TITLE
 Implementing commands to update acl of vdc and vapp

### PR DESCRIPTION
**Pull request by anusuyar**
Implementing commands to update acl of vdc and vapp.

Implementing add, remove, share, unshare, list acl commands for vdc and vapp.

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/160)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---

*[vcd_cli/catalog.py, line 453 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L305VOIxPYzSrfEcdQY:-L305VOIxPYzSrfEcdQZ:b6ebrcd) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L453)):*
> ```Python
>             catalog_name=catalog_name,
>             access_settings_list=acl_str_to_list_of_dict(access_list))
>         stdout('Access settings added to catalog.', ctx)
> ```

NIT: This message has a period whereas others do not. 

---

*[vcd_cli/catalog.py, line 486 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L305OrzmKiRtxwdlJtA:-L305OrzmKiRtxwdlJtB:b6ebrcd) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L486)):*
> ```Python
>             access_settings_list=acl_str_to_list_of_dict(access_list),
>             remove_all=all)
>         stdout('Access settings removed from catalog.', ctx)
> ```

NIT: This message has a period whereas others do not. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by hodgesrm** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 10 unresolved discussions, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by sahithi** [comment]
Reviewed 3 of 3 files at r1.
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[vcd_cli/catalog.py, line 444 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30ZnfVuUaoSK85PGyF:-L30ZnfVuUaoSK85PGyG:b-1eux16) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L444)):*
> ```Python
>                 nargs=-1,
>                 required=True)
> def add(ctx, catalog_name, access_list):
> ```

Please confirm the issue we saw in your previous demo is an actual issue from vCD and if yes, confirm bug has been filed. This is security loophole.
For other reviewers, issue-descirption:  vcd lets user to change the access-level of all the users in the org to Full Control while actually some users are given less-privileges. 

Anusuya, please feel free to re-phrase the problem statement based on your experimentation and analysis.

---

*[vcd_cli/catalog.py, line 453 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30X7u2cSBLPOEYYuEg:-L30X7u2cSBLPOEYYuEh:bipe8ic) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L453)):*
> ```Python
>             catalog_name=catalog_name,
>             access_settings_list=acl_str_to_list_of_dict(access_list))
>         stdout('Access settings added to catalog.', ctx)
> ```

Include catalog name in all the commands' output.

---

*[vcd_cli/catalog.py, line 513 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2fdxLQcNHp60IuPi4X:-L30WkjcPv6o5GRImkAC:b32v57) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L513)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

add org name enclosed with single quotes \'%s\'
</blockquote></details>

+1

---

*[vcd_cli/vapp.py, line 758 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Z_mEEAOpyM03AsUM:-L30Z_mEEAOpyM03AsUN:bl79zbj) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L758)):*
> ```Python
> @vapp.group(short_help='work with vapp acl')
> @click.pass_context
> def acl(ctx):
> ```

Info command is missing. Please add

---

*[vcd_cli/vapp.py, line 801 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XWEmYLQHElLBLKJF:-L30XWEnRtfQidR5BXTn:be2rhoh) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L801)):*
> ```Python
>                 nargs=-1,
>                 required=True)
> def add(ctx, vapp_name, access_list):
> ```

Add vdc an optional parameter.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XbDX5j7tXMvgad0c:-L30XbDX5j7tXMvgad0d:b-1u51tf) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
> ```Python
>               metavar='[all]',
>               help='remove all the access settings from the vapp')
> def remove(ctx, vapp_name, access_list, all):
> ```

Add vdc an optional parameter

---

*[vcd_cli/vapp.py, line 863 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XfpeEKnq4oeL6CjA:-L30XfpeEKnq4oeL6CjB:bvj97y8) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L863)):*
> ```Python
>               help='access level at which the vapp is shared. ReadOnly by'
>                    ' default')
> def share(ctx, vapp_name, access_level):
> ```

same vdc - optional param

---

*[vcd_cli/vapp.py, line 881 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Xj1U62JUbZ_dvXUH:-L30Xj1U62JUbZ_dvXUI:b-db5sgv) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L881)):*
> ```Python
> @click.argument('vapp-name',
>                 metavar='<vapp-name>')
> def unshare(ctx, vapp_name):
> ```

add vdc as an optional param

---

*[vcd_cli/vapp.py, line 898 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XvU5SzMXLNncg12D:-L30XvU5SzMXLNncg12E:b-db5sgv) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L898)):*
> ```Python
> @click.argument('vapp-name',
>                 metavar='<vapp-name>')
> def list_acl(ctx, vapp_name):
> ```

add vdc as an optional param

---

*[vcd_cli/vdc.py, line 85 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30YIEEMtW2Z0A8Ezy1:-L30YIEEMtW2Z0A8Ezy2:bwcblsp) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vdc.py#L85)):*
> ```Python
>             access_settings = vdc.get_access_settings()
>         except MissingLinkException:
>             pass
> ```

Why pass? You mean return? Either way, let stderr() throw appropriate message to the user.
(or) Get rid of the try catch block around access_settings and let stderr() handle it via catch block at entire command level

---

*[vcd_cli/vdc.py, line 364 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Z5op0ztVkCPo8RXx:-L30Z5op0ztVkCPo8RXy:btrpdub) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vdc.py#L364)):*
> ```Python
>         vdc.add_access_settings(
>             access_settings_list=acl_str_to_list_of_dict(access_list))
>         stdout('Access settings added to vdc.', ctx)
> ```

Include names of the entities in all commands' outputs

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 18 unresolved discussions, some commit checks failed.

---

*[vcd_cli/vapp.py, line 758 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Z_mEEAOpyM03AsUM:-L30joetm8P1TO6ysWhj:b-1e2v7c) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L758)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Info command is missing. Please add
</blockquote></details>

I think the `list` command shows all the information in the acl, if that is the case, info will not bring additional value

---

*[vcd_cli/vapp.py, line 801 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XWEmYLQHElLBLKJF:-L30k-E53wtW6OtmHMPe:b-fsth9m) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L801)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Add vdc an optional parameter.
</blockquote></details>

I think we should address the `vdc` option on a separate task, lets deliver this implementation first. We also need to discuss where is the `vdc` option being defined (vcd, vapp or acl levels)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by anusuyar** [comment]
Review status: 0 of 4 files reviewed at latest revision, 20 unresolved discussions.

---

*[vcd_cli/catalog.py, line 444 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30ZnfVuUaoSK85PGyF:-L30eeIXasIze3M3Xnt5:b-puloxi) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L444)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Please confirm the issue we saw in your previous demo is an actual issue from vCD and if yes, confirm bug has been filed. This is security loophole.
For other reviewers, issue-descirption:  vcd lets user to change the access-level of all the users in the org to Full Control while actually some users are given less-privileges. 

Anusuya, please feel free to re-phrase the problem statement based on your experimentation and analysis.
</blockquote></details>

I think this should not be a problem. We can give FullControl access to all org Members(global access-level) yet give only 'ReadOnly' to 1-2 users. 

---

*[vcd_cli/catalog.py, line 453 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L305VOIxPYzSrfEcdQY:-L30OYeb0BKnuB1djur4:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L453)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

NIT: This message has a period whereas others do not. 
</blockquote></details>

Done.

---

*[vcd_cli/catalog.py, line 453 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30X7u2cSBLPOEYYuEg:-L30diqWVjWC35Y3x-vi:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L453)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Include catalog name in all the commands' output.
</blockquote></details>

Done.

---

*[vcd_cli/catalog.py, line 486 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L305OrzmKiRtxwdlJtA:-L30OWfmtYo_NFogJzQX:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L486)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

NIT: This message has a period whereas others do not. 
</blockquote></details>

Done.

---

*[vcd_cli/catalog.py, line 513 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2fdxLQcNHp60IuPi4X:-L30zYCQDDQOL6wH13Zc:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L513)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 758 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Z_mEEAOpyM03AsUM:-L30ykiNV7tEljnjJQe7:b-d0wcu3) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L758)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I think the `list` command shows all the information in the acl, if that is the case, info will not bring additional value
</blockquote></details>

We decided to remove as acl list gives the same information

---

*[vcd_cli/vapp.py, line 766 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2feGirBc1rpNF5R-IU:-L30dl728BhyCsKvK3vv:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L766)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Create a Description section and move the description of the syntax for access settings into the description section. See example of `vcd vapp` command.

Add an example with group as well if that is supported

The description should also document the values that can be used in the `share` command and the default one.
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 772 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ferTFKjid_dzhSykN:-L30fcc6NBFL9UK7jO45:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L772)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

see note above
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 801 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XWEmYLQHElLBLKJF:-L30ytC-vKefAQqyTh5G:bmtvypo) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L801)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I think we should address the `vdc` option on a separate task, lets deliver this implementation first. We also need to discuss where is the `vdc` option being defined (vcd, vapp or acl levels)
</blockquote></details>

+1 paco.

---

*[vcd_cli/vapp.py, line 810 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ffr4b-96j9ytMaRa5:-L30ywqah71nme8qqx-2:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L810)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

include the name of the vapp in the message, enclosed in single quotes.
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L2i-SLTwVjFxi8LsScz:b-y8rnj7) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

as with the `delete` actions, `remove` should have a `--yes` option using click annotations, rather than coding the confirmation
</blockquote></details>

Removing 1 or 2 access setting is not a disruptive process similar to deleting an org/vm/vm.  adding an access setting and removing an access setting are an equivalent operation.  That's, why I didn't, add a prompt for normal remove. But 'remove_all' is a disruptive process . That's why I added a prompt specifically for it.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XbDX5j7tXMvgad0c:-L30yyoY-fMz4BeCJSPg:bfsfm9f) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Add vdc an optional parameter
</blockquote></details>

As paco had mentioned in other comment, we will deal with this option later

---

*[vcd_cli/vapp.py, line 863 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XfpeEKnq4oeL6CjA:-L30zP0Eho20128ZgknF:b-ql6elx) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L863)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

same vdc - optional param
</blockquote></details>

As paco had mentioned in other comment, we will deal with this option laterr

---

*[vcd_cli/vapp.py, line 871 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ffypPImofk5qOhk4b:-L2i-Emn849bV_33yqbM:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L871)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

include the name of the vapp and org in the message, enclosed in single quotes.
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 881 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Xj1U62JUbZ_dvXUH:-L30zQcSx2Jk0DwiVpwQ:bfsfm9f) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L881)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

add vdc as an optional param
</blockquote></details>

As paco had mentioned in other comment, we will deal with this option later

---

*[vcd_cli/vapp.py, line 889 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2fg4CEHrhNbrvFJKRB:-L2i-PjBnxKRMtwSN1gu:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L889)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

same
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 898 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30XvU5SzMXLNncg12D:-L30zRYRv-fx4f5IkQfv:bfsfm9f) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L898)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

add vdc as an optional param
</blockquote></details>

As paco had mentioned in other comment, we will deal with this option later

---

*[vcd_cli/vdc.py, line 85 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30YIEEMtW2Z0A8Ezy1:-L30eAc9moam9RoQ06XQ:bcmduvu) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vdc.py#L85)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Why pass? You mean return? Either way, let stderr() throw appropriate message to the user.
(or) Get rid of the try catch block around access_settings and let stderr() handle it via catch block at entire command level
</blockquote></details>

if for some reason, get_access_setting throws an exception, we don't want to fail the whole vdc info command.  We want to show other vdc-info except acl info in that case

---

*[vcd_cli/vdc.py, line 304 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2fgE84AQS0lBOSvDYM:-L30hM7JoLMeBlugPFd0:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vdc.py#L304)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

see my comments on the vapp command
</blockquote></details>

Done.

---

*[vcd_cli/vdc.py, line 364 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30Z5op0ztVkCPo8RXx:-L30hLeN4H9Hue0iToQ2:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vdc.py#L364)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Include names of the entities in all commands' outputs
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 4 of 4 files at r2.
Review status: all files reviewed at latest revision, 11 unresolved discussions.

---

*[vcd_cli/catalog.py, line 444 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L30ZnfVuUaoSK85PGyF:-L327QnwNKYAT-soQArm:b-lumctp) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/catalog.py#L444)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think this should not be a problem. We can give FullControl access to all org Members(global access-level) yet give only 'ReadOnly' to 1-2 users. 
</blockquote></details>

Marking this as resolved assuming enough testing has been done.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L3289m1Hmcy9HN45GC4:bfdf1cu) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Removing 1 or 2 access setting is not a disruptive process similar to deleting an org/vm/vm.  adding an access setting and removing an access setting are an equivalent operation.  That's, why I didn't, add a prompt for normal remove. But 'remove_all' is a disruptive process . That's why I added a prompt specifically for it.
</blockquote></details>

+1 paco
It can be disruptive to that one User who got removed.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-:-L329FN_LYu41lDFZpDG:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L33b1O6EYSzVDgSlBZe:b-ledrhn) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

+1 paco
It can be disruptive to that one User who got removed.
</blockquote></details>

If a vApp has only 1 ACL, it will get a prompt if using `--all`, but won't get any prompt if removing it individually. I would prefer to ask for confirmation in any case. If not, we would be making differences with other commands that ask for confirmation when deleting/removing individual items...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by pacogomez** [comment]
:lgtm: except for the confirmation prompt when removing ACLs

---

Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-:-L33cCOMR9kF9rqCmHAn:b-xovyi7)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L34eKtUjv2wcmnCJSAy:b-95y0bc) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

If a vApp has only 1 ACL, it will get a prompt if using `--all`, but won't get any prompt if removing it individually. I would prefer to ask for confirmation in any case. If not, we would be making differences with other commands that ask for confirmation when deleting/removing individual items...
</blockquote></details>

As discussed offline with Anusuya, I prefer two prompts in implementation. One general prompt and one specific to -all flag

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L34m5MyFKlZs-jdBQ3l:b-f0ktgx) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

As discussed offline with Anusuya, I prefer two prompts in implementation. One general prompt and one specific to -all flag
</blockquote></details>

Hi all.  Regardless of how prompts are implemented there should be a why to suppress them easily using something like --force.  

Is that the case here as well as for other commands? 

If not you may not be able to issue commands reliably from within scripts or in cases where you don't have a tty.  When scripting the command might be in a loop or you might open using a pipe, which is pretty common for scripting languages.  Also commands of the form 'ssh some.host command' have weird tty behavior. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by sahithi** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L34saqSXigbc-c8zLIk:bqk8dwf) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Hi all.  Regardless of how prompts are implemented there should be a why to suppress them easily using something like --force.  

Is that the case here as well as for other commands? 

If not you may not be able to issue commands reliably from within scripts or in cases where you don't have a tty.  When scripting the command might be in a loop or you might open using a pipe, which is pretty common for scripting languages.  Also commands of the form 'ssh some.host command' have weird tty behavior. 
</blockquote></details>

Valid point by Robert. I see something like --force (or) --suppress-prompts set once at global level takes effect for all further commands

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by anusuyar** [comment]
Review status: 1 of 4 files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L34ttT1quy3_BKMv7vT:b-hl42p9) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Valid point by Robert. I see something like --force (or) --suppress-prompts set once at global level takes effect for all further commands
</blockquote></details>

There is also  Linux command called yes that will provide 'y' for all prompts.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Comment by pacogomez** [comment]
Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions, some commit checks failed.

---

*[vcd_cli/vapp.py, line 828 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/160#-L2ff0siNZRpaM5McVv1:-L35FDp7p3b-FRxsMwI5:bvvbzwp) ([raw file](https://github.com/vmware/vcd-cli/blob/194fd904459202ac0746c4e9266987c4c629a7e7/vcd_cli/vapp.py#L828)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

There is also  Linux command called yes that will provide 'y' for all prompts.
</blockquote></details>

`--yes` should only be applied to 'potentially destructive' actions like `delete` `remove`, it shouldn't apply globally to all commands. I think it makes sense to introduce this option on a per-command basis like here.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/160)*

**Pull request merged**
