### PR TITLE
[VCDA-605] Added optional root_folder parameter to attach VC

### PR DESCRIPTION
**Pull request by ckolovson**
- Added optional root_folder parameter to attach VC

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/212)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

Somewhat related--I would recommend using a branch for future commits as your PR shows a bunch of unrelated commits.  

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/212#-:-LAQboSdDu01Dhg9zpHF:b5e2jxe)*

**Comment by ckolovson** [comment]
Thanks for the suggestion. 

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/212#-:-LAQe692Ej6eL9C_vtFd:b-yr7bv6)*

**Comment by rocknes** [comment]
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---

*[vcd_cli/vc.py, line 39 at r1](https://reviewable.io/reviews/vmware/vcd-cli/212#-LAzfssA2pelWqRK5e5R:-LAzfssB8yhuoR2vDSd2:b-l3ny4j) ([raw file](https://github.com/vmware/vcd-cli/blob/acd049b18cacca80fcf1ccadd74e62dee0959c79/vcd_cli/vc.py#L39)):*
> ```Python
> \b
>         vcd vc attach vc-name
>             --vc-host 'VC-host-FQDN-or-IP-address'
> ```

I think we should provide concrete values in the example usage section. Instead of VC-host-FQDN we should say vc.server.example.com or something similar.

Also we shouldn't use single quotes in values, since they won't work on win platform.

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/212)*

**Comment by ckolovson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/vc.py, line 39 at r1](https://reviewable.io/reviews/vmware/vcd-cli/212#-LAzfssA2pelWqRK5e5R:-LB1w_5gAAQQVczBh-FM:b76tbwt) ([raw file](https://github.com/vmware/vcd-cli/blob/acd049b18cacca80fcf1ccadd74e62dee0959c79/vcd_cli/vc.py#L39)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

I think we should provide concrete values in the example usage section. Instead of VC-host-FQDN we should say vc.server.example.com or something similar.

Also we shouldn't use single quotes in values, since they won't work on win platform.
</blockquote></details>

Not sure what you mean about single quotes in help text. They are used all over our code. Please advise. 

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/212)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/vc.py, line 39 at r1](https://reviewable.io/reviews/vmware/vcd-cli/212#-LAzfssA2pelWqRK5e5R:-LB3OTmn6qQir5N4bv4B:b647813) ([raw file](https://github.com/vmware/vcd-cli/blob/acd049b18cacca80fcf1ccadd74e62dee0959c79/vcd_cli/vc.py#L39)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Made changes regarding vc.server.example.com or something similar.
</blockquote></details>

We use quotes to escape space in input. I think it's ok to stick to single quotes in cases where quotes are required, but I will suggest to remove quotes all togather where they are not required viz. when input string doesn't have space.

Btw just to demonstrate that single quotes don't work on win, I ran a small test

(vcd-cli) C:\code\vcd-cli>vcd catalog list
creationDate              isPublished    isShared    name        numberOfMedia    numberOfTemplates  orgName                   ownerName
------------------------  -------------  ----------  --------  ---------------  -------------------  ------------------------  --------------
2018-04-20T19:26:14.668Z  false          false       test-cat                0                    1  pyvcloud-system-test-org  catalog_author

(vcd-cli) C:\code\vcd-cli>vcd catalog list test-cat
catalogName    entityType    isPublished    name                    ownerName       status      storageKB  vdcName
-------------  ------------  -------------  ----------------------  --------------  --------  -----------  ----------------------------
test-cat       vapptemplate  false          test_vapp_template.ova  catalog_author  RESOLVED           40  pyvcloud-system-test-org-vdc

(vcd-cli) C:\code\vcd-cli>vcd catalog list 'test-cat'
not found

(vcd-cli) C:\code\vcd-cli>vcd catalog list "test-cat"
catalogName    entityType    isPublished    name                    ownerName       status      storageKB  vdcName
-------------  ------------  -------------  ----------------------  --------------  --------  -----------  ----------------------------
test-cat       vapptemplate  false          test_vapp_template.ova  catalog_author  RESOLVED           40  pyvcloud-system-test-org-vdc

---


*Comments from [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/212#-:-LB3PZ1v9NX2x66tZUrE:bnfp4nl)*

**Pull request merged**
