### PR TITLE
VCDA-248 error handling on invalid session

### PR DESCRIPTION
**Pull request by pacogomez**
- more meaningfull error messages when session invalid
- nicer display of tables when cells contain lists
- PEP8 formatting of the updated files only

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/162)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/utils.py, line 193 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L3-yH1c9mF0PQRpnC1I:-L3-yH1c9mF0PQRpnC1J:blffjbm) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L193)):*
> ```Python
>             elif not isinstance(obj, list):
>                 obj1 = {}
>                 for k, v in obj.items():
> ```

Can you add a command to say what these two loops are doing?  I would guess it's addressing list display in property/value output, but it's hard to read that behavior out of the code. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162)*

**Comment by pacogomez** [comment]
Review status: 0 of 2 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/utils.py, line 193 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L3-yH1c9mF0PQRpnC1I:-L30LSyAa8ikbD0lXqR-:b-20jqh) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L193)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Can you add a command to say what these two loops are doing?  I would guess it's addressing list display in property/value output, but it's hard to read that behavior out of the code. 
</blockquote></details>

it displays a value per line when the cell in the table is multi-valued, it results in a nicer table formatting

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162)*

**Comment by sahithi** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/utils.py, line 221 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L30O1Sdc8hOmuRMMAam:-L30O1Sdc8hOmuRMMAan:bs2mpcm) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L221)):*
> ```Python
>     if type(exception) == VcdErrorResponseException:
>         if exception.status_code == 401:
>             message = 'Session has expired or is invalid, please login again.'
> ```

Above message does not suit well to the case where user provides invalid credentials at first attempt.
How about "Authentication failed (or) Invalid session"

---

*[vcd_cli/utils.py, line 230 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L30OmWahgugtIWFO3D_:-L30OmWbM2gjoz14W0Ga:br6ky4c) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L230)):*
> ```Python
>         else:
>             message = str(exception)
>     elif type(exception) == MissingLinkException:
> ```

I think processing Exceptions (like MissingLInk, MultipleLinks etc) emerging from vcd-cli/pyvcloud to convey more meaningful messages is necessary.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/utils.py, line 193 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L3-yH1c9mF0PQRpnC1I:-L30PYERR8_3yqeUEO9G:byjgjhk) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L193)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

it displays a value per line when the cell in the table is multi-valued, it results in a nicer table formatting
</blockquote></details>

I don't think we want to do that.  You can't get the values with grep any more, which cuts out using it for scripting. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/utils.py, line 193 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L3-yH1c9mF0PQRpnC1I:-L30Z2MsxL6PT5L6EgOl:b-ohgjcn) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L193)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

I don't think we want to do that.  You can't get the values with grep any more, which cuts out using it for scripting. 
</blockquote></details>

I think text output (table or prop/value list) should be optimized for legibility, users should use `--output json` for scripting for more precise output manipulation

---

*[vcd_cli/utils.py, line 221 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L30O1Sdc8hOmuRMMAam:-L30kpiDwn3ZSTXXkKkR:b-l0sfk8) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L221)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Above message does not suit well to the case where user provides invalid credentials at first attempt.
How about "Authentication failed (or) Invalid session"
</blockquote></details>

this exception addresses the invalid session, for invalid login is caught in the client with the message 'Login Failed'

---

*[vcd_cli/utils.py, line 230 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L30OmWahgugtIWFO3D_:-L30lcVuIYkacnPMHzZ6:bhc5dlq) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L230)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

I think processing Exceptions (like MissingLInk, MultipleLinks etc) emerging from vcd-cli/pyvcloud to convey more meaningful messages is necessary.
</blockquote></details>

Agreed, but the scope of this task was the invalid session.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-:-L34QdSA-bjIPlLqBzkD:bnfp4nl)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vcd_cli/utils.py, line 193 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L3-yH1c9mF0PQRpnC1I:-L35kIEpDT5R-mhrf71p:b-bvju4n) ([raw file](https://github.com/vmware/vcd-cli/blob/e872dbba38949664b90c3fd8fb70d6b2b5597e71/vcd_cli/utils.py#L193)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I think text output (table or prop/value list) should be optimized for legibility, users should use `--output json` for scripting for more precise output manipulation
</blockquote></details>

Can you please update the commit with few examples? Otherwise the change looks good.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-:-L35kONBRNOuyo1Gyt4V:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---

*[vcd_cli/utils.py, line 193 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-L3-yH1c9mF0PQRpnC1I:-L35wDkyzAXB9uunv4TB:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/82366500af3bf658ebc93148997ebcad683bc7e2/vcd_cli/utils.py#L193)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Can you please update the commit with few examples? Otherwise the change looks good.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162)*

**Comment by pacogomez** [comment]
can't format in fixed width font

---

Review status: all files reviewed at latest revision, 1 unresolved discussion, some commit checks failed.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/162#-:-L35wFkvspWLuu72w7M-:b-3elje9)*

**Pull request merged**
