### PR TITLE
VCDA-369: Implementing commands to create isolated OrgVDC networks.

### PR DESCRIPTION
**Pull request by rocknes**
* Implemened commands to create isolated OrgVDC networks.
* Ran yapf on network.py for formatting

Manual run the command,
(vcd-cli) c:\code\vcd-cli\vcd_cli>vcd network isolated create iso-net1 -d "Dummy description" -g 192.168.1.1 -n 255.255.255.0
networkCreateOrgVdcNetwork: Creating Network iso-net1(167f0b16-6122-4a29-8980-7062abe9dcb7)
networkCreateOrgVdcNetwork: Creating Network iso-net1(167f0b16-6122-4a29-8980-7062abe9dcb7)
task: bd8da4ca-0180-49d1-b335-f635681b8093, Created Network iso-net1(167f0b16-6122-4a29-8980-7062abe9dcb7), result: success

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/161)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161)*

**Comment by pacogomez** [comment]
typo and cosmetic changes

---

Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[vcd_cli/network.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmOaigpno6yQclon3:-L2fmOaigpno6yQclon4:b-wnw6dv) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L44)):*
> ```Python
> \b
>     Examples
>         vcd network direct create 'direct-net1' \\
> ```

this name doesn't need single quotes (at least on *nix) systems, is it required in windows? if not, don't enclose it

---

*[vcd_cli/network.py, line 47 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmaa41eCq-uiojhir:-L2fmaa41eCq-uiojhis:bddmtk9) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L47)):*
> ```Python
>             --description 'directly connected orgvdc network' \\
>             --parent 'ext-net1'
>             Create an org vdc network which is directly connected \\
> ```

Descriptions don't required backslash

---

*[vcd_cli/network.py, line 65 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fkLDw7t0eJF8N7u_s:-L2fkLDw7t0eJF8N7u_t:b-fo5xsv) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L65)):*
> ```Python
>     Examples
>         vcd network isolated create "isolated-net1" \\
>              --gateway-ip 192.168.1.1 --netmask 255.255.255.0 \\
> ```

align margin with the rest of lines. Using single quotes is preferred to double quotes to be consistent with the rest of the  documentation.

---

*[vcd_cli/network.py, line 72 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmr_QuBuJp9yQwzWT:-L2fmr_QuBuJp9yQwzWU:b-4v86ek) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L72)):*
> ```Python
>             --max-lease-time 7200 --dhcp-ip-range-start 192.168.1.100 \\
>             --dhcp-ip-range-end 192.168.1.199
>             Creates an isolated org vdc network with an inbuilt dhcp service.
> ```

`Create` is preferred. 

---

*[vcd_cli/network.py, line 152 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fm8sK991ZhCbwAlHd:-L2fm8sK991ZhCbwAlHe:bmdu6tz) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L152)):*
> ```Python
>     '--description',
>     'description',
>     required=False,
> ```

required is False if not specified, no need to add it here

---

*[vcd_cli/network.py, line 161 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2flyLILgi1B0ydtOHn:-L2flyLILgi1B0ydtOHo:bs6t0rk) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L161)):*
> ```Python
>     required=False,
>     metavar='<ip>',
>     help='IP of the primary DNS server')
> ```

use of the dot at the end is inconsistent, some have it, some don't

---

*[vcd_cli/network.py, line 225 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2flr6WS6e3EwwN8aIr:-L2flr6WS6e3EwwN8aIs:bb7phvt) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L225)):*
> ```Python
>     required=False,
>     default=False,
>     help='Share/Don\'t share the netowrk with other VDC(s) in the '
> ```

typo

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-:-L2fnBVdjbH28Q4IaQmA:b-p1z5ny)*

**Comment by rocknes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions, all commit checks successful.

---

*[vcd_cli/network.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmOaigpno6yQclon3:-L2hAdOG3fO5welahVo8:b-cy1p4m) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L44)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

this name doesn't need single quotes (at least on *nix) systems, is it required in windows? if not, don't enclose it
</blockquote></details>

Removed single quotes

---

*[vcd_cli/network.py, line 47 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmaa41eCq-uiojhir:-L2hCE5BabU7kDNZOdYo:bbthybo) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L47)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Descriptions don't required backslash
</blockquote></details>

Removed backslashs from description

---

*[vcd_cli/network.py, line 65 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fkLDw7t0eJF8N7u_s:-L2hJMDThPPSVtoPUEII:bx3iq6m) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L65)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

align margin with the rest of lines. Using single quotes is preferred to double quotes to be consistent with the rest of the  documentation.
</blockquote></details>

Addressed

---

*[vcd_cli/network.py, line 72 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmr_QuBuJp9yQwzWT:-L2hJOAP1zmTMgdQ-3vt:b4r40en) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L72)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

`Create` is preferred. 
</blockquote></details>

Dropped the extra s

---

*[vcd_cli/network.py, line 152 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fm8sK991ZhCbwAlHd:-L2hKWsiFJXQFOpinDRk:ba3dfob) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L152)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

required is False if not specified, no need to add it here
</blockquote></details>

Removed

---

*[vcd_cli/network.py, line 161 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2flyLILgi1B0ydtOHn:-L2hKYfY6glvdd6Z8sjl:b4k422r) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L161)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

use of the dot at the end is inconsistent, some have it, some don't
</blockquote></details>

Removed full-stop from the end of all option help messages

---

*[vcd_cli/network.py, line 225 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2flr6WS6e3EwwN8aIr:-L2hKgiwmLAtzU2lQ2el:b-886gsx) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L225)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

typo
</blockquote></details>

Fixed

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161)*

**Comment by pacogomez** [comment]
Review status: 0 of 1 files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/network.py, line 47 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmaa41eCq-uiojhir:-L2i4zVlE_8ZC92HCoDL:br2e3mj) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L47)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Removed backslashs from description
</blockquote></details>

Sorry for the confusion, but examples do need double backslash, as they will show with a single backslash in the help to indicate that it is considered one single line by the shell. But the description below the example, if it spans two or more lines, don't need any backslash because is regular text, not shell input. see `vcd vapp` and `vcd search` as examples

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161)*

**Comment by pacogomez** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/network.py, line 65 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fkLDw7t0eJF8N7u_s:-L2mVcvIh79ls6Vb3-Ts:b1tourk) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L65)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Addressed
</blockquote></details>

Just keep the 2x backlashes in the sample unix command, no the description below. The rest looks good

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161)*

**Comment by anusuyar** [comment]
:lgtm: after addressing comments

---

Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/network.py, line 159 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L357AJqMAXR45gMlohV:-L357AJqMAXR45gMlohW:b-qk7ee) ([raw file](https://github.com/vmware/vcd-cli/blob/b69c02f8f3af300e385000424ffd9ac1afc8f593/vcd_cli/network.py#L159)):*
> ```Python
>     '--dns2',
>     'secondary_dns_ip',
>     metavar='<ip>',
> ```

 metavar for dn1 and dn2 should be different?

---

*[vcd_cli/network.py, line 164 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L357McWyOt-yheWaRa-:-L357McXgytB-n2Jl_fp:b41vvyq) ([raw file](https://github.com/vmware/vcd-cli/blob/b69c02f8f3af300e385000424ffd9ac1afc8f593/vcd_cli/network.py#L164)):*
> ```Python
>     '--dns-suffix',
>     'dns_suffix',
>     metavar='<name>',
> ```

metavar for should not be <name> here.

---

*[vcd_cli/network.py, line 169 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L359392XzSRgdM5ct-6:-L359392XzSRgdM5ct-7:ba2by7g) ([raw file](https://github.com/vmware/vcd-cli/blob/b69c02f8f3af300e385000424ffd9ac1afc8f593/vcd_cli/network.py#L169)):*
> ```Python
>     '--ip-range-start',
>     'ip_range_start',
>     metavar='<>',
> ```

We can remove '<>' here and click will use the default metavar value

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-:-L359TPbK_obEtAEVsqR:b-98fkod)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161)*

**Comment by rocknes** [comment]
Review status: 0 of 1 files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/network.py, line 47 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fmaa41eCq-uiojhir:-L35Cg9foHpQMBUwW_Bd:btn461w) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L47)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Sorry for the confusion, but examples do need double backslash, as they will show with a single backslash in the help to indicate that it is considered one single line by the shell. But the description below the example, if it spans two or more lines, don't need any backslash because is regular text, not shell input. see `vcd vapp` and `vcd search` as examples
</blockquote></details>

Got it

---

*[vcd_cli/network.py, line 65 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L2fkLDw7t0eJF8N7u_s:-L35Chwpeqjv9B7gsJr7:bb6un1j) ([raw file](https://github.com/vmware/vcd-cli/blob/4d70e57e5ff1c6cb3bfcc5e458955dcb58eff79a/vcd_cli/network.py#L65)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

Just keep the 2x backlashes in the sample unix command, no the description below. The rest looks good
</blockquote></details>

Done

---

*[vcd_cli/network.py, line 159 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L357AJqMAXR45gMlohV:-L35AvaTUOAOPUnKcC0E:b-2v2lb5) ([raw file](https://github.com/vmware/vcd-cli/blob/b69c02f8f3af300e385000424ffd9ac1afc8f593/vcd_cli/network.py#L159)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

 metavar for dn1 and dn2 should be different?
</blockquote></details>

The help will look like 

--dns1 \<ip\>
--dns2 \<ip\>

which in my opinion is the correct way to list help. However Paco wanted us to have a broader discussion on metavar and how we should standardize them.

---

*[vcd_cli/network.py, line 164 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L357McWyOt-yheWaRa-:-L35BOOhI22v60DvhiBF:bxofwfe) ([raw file](https://github.com/vmware/vcd-cli/blob/b69c02f8f3af300e385000424ffd9ac1afc8f593/vcd_cli/network.py#L164)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

metavar for should not be <name> here.
</blockquote></details>

I guess your comment got clipped can you please escape angle brackets with \\

---

*[vcd_cli/network.py, line 169 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-L359392XzSRgdM5ct-6:-L35BULmABr5MBtTTr3A:b68qk28) ([raw file](https://github.com/vmware/vcd-cli/blob/b69c02f8f3af300e385000424ffd9ac1afc8f593/vcd_cli/network.py#L169)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

We can remove '<>' here and click will use the default metavar value
</blockquote></details>

Default metavar is TEXT which is wrong in this case, metavar should be \<ip\>. I missed it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/161#-:-L35EKbZMlsB1M6HJvov:bnfp4nl)*

**Pull request merged**
