### PR TITLE
VCDA-236 Create empty vApp and add VMs

### PR DESCRIPTION
**Pull request by pacogomez**
```
$ vcd vapp create vapp1 --network net1
task: 0790bd41-1049-4e8f-81ef-d76db12b8ef3, Composed Virtual Application vapp1(26644133-6d17-4c8a-8f6e-9b732fa75ca4), result: success

$ vcd vapp add-vm vapp1 k8s-u.ova csetmp-u -c cse --target-vm node-abbcf --hostname node-abbcf --storage-profile Development --network net1
task: 9581e4df-264c-4f74-abe0-81f890adcdc7, Recomposed Virtual Application vapp1(26644133-6d17-4c8a-8f6e-9b732fa75ca4), result: success
```

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/143)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/vapp.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0fz-sHVbwjYqHSx8HO:-L0fz-sIr2Wgp2aYgtp4:b3md55x) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L44)):*
> ```Python
>         in the currect vDC.
> \b
>         'vapp add-vm' adds VMs to the vApp. When '--catalog' is used, the
> ```

adds VM (singular) to the vApp.

---

*[vcd_cli/vapp.py, line 586 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0g2dWmKcMoZ_pzpri2:-L0g2dWmKcMoZ_pzpri3:bpvu9nv) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L586)):*
> ```Python
> @vapp.command('add-vm', short_help='add VM to vApp')
> @click.pass_context
> @click.argument('name',
> ```

'vapp-name' or 'target-vapp' sounds better instead of 'name'? I confused it with the vm-name at first.

---

*[vcd_cli/vapp.py, line 623 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0g32pcC6_ybvbm9tme:-L0g32pd236r1fcypTlZ:baeuyl3) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L623)):*
> ```Python
>               metavar='storage-profile',
>               help='Name of the storage profile for the VM')
> def add_vm(ctx, name, source_vapp, source_vm, catalog, target_vm, hostname,
> ```

Shouldn't we let this command make use of 'vapp-in-use' if target vApp is not specified?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143)*

**Comment by anusuyar** [comment]
Reviewed 20 of 20 files at r1.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/vapp.py, line 109 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gHOo-wvMSSKUkhK8Z:-L0gHOo-wvMSSKUkhK8_:b-s9o8yf) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L109)):*
> ```Python
> \b
>         vcd vapp add-vm vapp1 template1.ova vm1 -c catalog1
>             Add a VM to a vApp.
> ```

Can we  expand on this description more, like 
Add a VM from a source vapp to a target vapp etc?

---

*[vcd_cli/vapp.py, line 235 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gJIwP_UwBBXpRm9o5:-L0gJIwP_UwBBXpRm9o6:b59vyo1) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L235)):*
> ```Python
>                 required=True)
> @click.option('-d',
>               '--description',
> ```

add help for all options.

---

*[vcd_cli/vapp.py, line 586 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0g2dWmKcMoZ_pzpri2:-L0gISMrPnGGv4MRVeBR:b-7wbn0j) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L586)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

'vapp-name' or 'target-vapp' sounds better instead of 'name'? I confused it with the vm-name at first.
</blockquote></details>

^ +1

---

*[vcd_cli/vapp.py, line 597 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gH1hl6Cn96au-ZpWd:-L0gH1hl6Cn96au-ZpWe:buapm7f) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L597)):*
> ```Python
> @click.option('-c',
>               '--catalog',
>               metavar='<name>')
> ```

add help info for catalog

---

*[vcd_cli/vapp.py, line 623 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0g32pcC6_ybvbm9tme:-L0gJXsT_Sl8WWZ8HvFv:b95im30) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L623)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Shouldn't we let this command make use of 'vapp-in-use' if target vApp is not specified?
</blockquote></details>

i think we should not assume that the user wants to add the vapp in the 'vapp-in-use'.   I can see a senario where a  user  swtich to vapp1 for some workflow and now wants to add a vm to vapp2. 

if he forgets to switch the vapp to vapp2 and tried to use the command add_vm without target_vapp name , the vm will be added to vapp1 instead of vapp2. And he would not know that the vm is added to a wrong vapp. 

---

*[vcd_cli/vapp.py, line 641 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gKrOv-UwDxaLBgDZn:-L0gKrOv-UwDxaLBgDZo:bsdi7dx) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L641)):*
> ```Python
>         vapp = VApp(client, resource=vapp_resource)
>         assert source_vapp_resource is not None
>         spec = {'source_vm_name': source_vm, 'vapp': source_vapp_resource}
> ```

if possible we should name spec to be more specific. like vm_spec etc.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/vapp.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0fz-sHVbwjYqHSx8HO:-L0lL3e5Oyit5fHruMU-:b1w0te8) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L44)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

adds VM (singular) to the vApp.
</blockquote></details>

I will update it

---

*[vcd_cli/vapp.py, line 109 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gHOo-wvMSSKUkhK8Z:-L0lNB9bNkD9BwexFuH-:bb7f2mf) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L109)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Can we  expand on this description more, like 
Add a VM from a source vapp to a target vapp etc?
</blockquote></details>

done

---

*[vcd_cli/vapp.py, line 586 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0g2dWmKcMoZ_pzpri2:-L0lUWP-Fdd6Eywwetx9:b-7ql1td) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L586)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

^ +1
</blockquote></details>

fixed

---

*[vcd_cli/vapp.py, line 597 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gH1hl6Cn96au-ZpWd:-L0lUXXwMSwd44uhzJuB:b-7ql1td) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L597)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

add help info for catalog
</blockquote></details>

fixed

---

*[vcd_cli/vapp.py, line 623 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0g32pcC6_ybvbm9tme:-L0lUe-hcsCqlSZ4OPBr:byupht2) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L623)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

i think we should not assume that the user wants to add the vapp in the 'vapp-in-use'.   I can see a senario where a  user  swtich to vapp1 for some workflow and now wants to add a vm to vapp2. 

if he forgets to switch the vapp to vapp2 and tried to use the command add_vm without target_vapp name , the vm will be added to vapp1 instead of vapp2. And he would not know that the vm is added to a wrong vapp. 
</blockquote></details>

Let's have the user specify the target and source vApps in the command line explicitly, so we can avoid any confusion.

---

*[vcd_cli/vapp.py, line 641 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gKrOv-UwDxaLBgDZn:-L0lUySYA52rx3Hrz7iM:bhaox3j) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L641)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

if possible we should name spec to be more specific. like vm_spec etc.
</blockquote></details>

from the context, it is understood it is a vm spec, I prefer to keep it short

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/vapp.py, line 235 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0gJIwP_UwBBXpRm9o5:-L0lV6O9uCD5lN3lKPRb:bb7f2mf) ([raw file](https://github.com/vmware/vcd-cli/blob/12f617c140303c6473d4133cd1bf7251df3fe6f9/vcd_cli/vapp.py#L235)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

add help for all options.
</blockquote></details>

done

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-:-L0lYFkPXDTeTHc7Bagh:bnfp4nl)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 6 unresolved discussions, some commit checks failed.

---

*[vcd_cli/vapp.py, line 41 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0qSv6G8JXutTUS7Rel:-L0qSv6HkRdtFVtVUOR1:br7yfp7) ([raw file](https://github.com/vmware/vcd-cli/blob/f8b1a3a791e109cbe779bf626570297228c763b9/vcd_cli/vapp.py#L41)):*
> ```Python
>         'vapp create' creates new vApps. When '--catalog' and '--template' are
>         not provided, it creates an empty vApp and VMs can be added later.
>         When specifying a template in a catalog, it instantiates the template
> ```

"The resulting vApp is instantiated in the current VDC."

I think irrespective of the fact that we specify a template or not, the vApp is created in the current VDC.

---

*[vcd_cli/vapp.py, line 271 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0qTv9lshZxUpXdzbq1:-L0qTv9lshZxUpXdzbq2:b-k3e4k6) ([raw file](https://github.com/vmware/vcd-cli/blob/f8b1a3a791e109cbe779bf626570297228c763b9/vcd_cli/vapp.py#L271)):*
> ```Python
>               type=click.INT,
>               help='Amount of memory in MB')
> @click.option('-u',
> ```

We should start documenting this in Anusuya's wiki page, so that parity is maintained between different commands.

---

*[vcd_cli/vapp.py, line 650 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0qUf4-Nno5LtF_G0xl:-L0qUf4-Nno5LtF_G0xm:b-q5hqrc) ([raw file](https://github.com/vmware/vcd-cli/blob/f8b1a3a791e109cbe779bf626570297228c763b9/vcd_cli/vapp.py#L650)):*
> ```Python
>         vapp_resource = vdc.get_vapp(name)
>         vapp = VApp(client, resource=vapp_resource)
>         assert source_vapp_resource is not None
> ```

The assert should be moved to the line, right after the if-else block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-:-L0qV0tfTF1vqHqrlrJf:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: 1 of 58 files reviewed at latest revision, 6 unresolved discussions.

---

*[vcd_cli/vapp.py, line 41 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0qSv6G8JXutTUS7Rel:-L0qjw0jlUF79BOi9Hn_:b-yk3fis) ([raw file](https://github.com/vmware/vcd-cli/blob/f8b1a3a791e109cbe779bf626570297228c763b9/vcd_cli/vapp.py#L41)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

"The resulting vApp is instantiated in the current VDC."

I think irrespective of the fact that we specify a template or not, the vApp is created in the current VDC.

</blockquote></details>

I have rephrased it for clarity

---

*[vcd_cli/vapp.py, line 271 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0qTv9lshZxUpXdzbq1:-L0qk4Qtzykn5_condPv:b-7tdf7d) ([raw file](https://github.com/vmware/vcd-cli/blob/f8b1a3a791e109cbe779bf626570297228c763b9/vcd_cli/vapp.py#L271)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should start documenting this in Anusuya's wiki page, so that parity is maintained between different commands.
</blockquote></details>

agree

---

*[vcd_cli/vapp.py, line 650 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/143#-L0qUf4-Nno5LtF_G0xl:-L0qkVD4OxiqT9vYdt26:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/f8b1a3a791e109cbe779bf626570297228c763b9/vcd_cli/vapp.py#L650)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

The assert should be moved to the line, right after the if-else block.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/143)*

**Pull request merged**
