### PR TITLE
VCDA-365,366: Shutdown and Reboot a vapp/VM

### PR DESCRIPTION
**Pull request by sompa**
Includes SDK methods for rebooting and shutting down a vapp or VM(s) within a vapp

Added SDK methods for rebooting a vApp/VM
Added SDK methods for shutting down a vApp/VM
Added required unit tests.

**Command** : **vcd vapp shutdown sompa-vapp**
```
Are you sure you want to shutdown the vApp? [y/N]: y
vappShutdownGuest: Shutting down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
vappShutdownGuest: Shutting down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
task: 0df63085-0b7a-4bf4-9c46-203d2979655e, Shut down Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9), result: success


```
**Command:** **vcd vapp shutdown sompa-vapp vm3**
```
Are you sure you want to shutdown the vApp? [y/N]: y
vappShutdownGuest: Shutting down Virtual Machine vm3(afe0a16d-2750-43ec-a779-73073d12088c)
task: bd97d769-4de7-47b1-b5e5-49c9bf258cb7, result: error, message: [ 21bbfe02-5ce1-4247-bccc-f2f25b214d26 ] null
 - Cannot complete operation because VMware Tools is not running in this virtual machine.
(vcd-cli) malakars-m01:vcd-cli malakars$ vcd vapp reboot sompa-vapp vm3
Are you sure you want to reboot the vApp or VM(s)? [y/N]: y
vappRebootGuest: Rebooting Virtual Machine vm3(afe0a16d-2750-43ec-a779-73073d12088c)
task: f7ede655-0f53-404e-b216-e40e1a3085a6, result: error, message: [ 4d2e708f-cc9e-4f8e-8d95-bc67dc3d8fce ] Internal Server Error
 - Failed to reboot guest os for the VM "vm3 (afe0a16d-2750-43ec-a779-73073d12088c)" as required VM tools were found unavailable.
 - Cannot complete operation because VMware Tools is not running in this virtual machine.
```
**Command : vcd vapp reboot sompa-vapp**
```
Are you sure you want to reboot the vApp or VM(s)? [y/N]: y
vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
vappRebootGuest: Rebooting Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9)
task: 85ed6d2b-eb0f-4199-99bf-bc4b7d6a64eb, Reboot Virtual Application sompa-vapp(e332aacb-9a80-4aed-860c-af7de0ca10e9), result: success

```
**Command : vcd vapp reboot sompa-vapp vm3**
```
Are you sure you want to reboot the vApp or VM(s)? [y/N]: y
vappRebootGuest: Rebooting Virtual Machine vm3(afe0a16d-2750-43ec-a779-73073d12088c)
task: 3d07779b-4849-4ad7-bfc2-686af445a04f, result: error, message: [ 94940880-d9e0-41b6-80db-7c04a56f7f28 ] Internal Server Error
 - Failed to reboot guest os for the VM "vm3 (afe0a16d-2750-43ec-a779-73073d12088c)" as required VM tools were found unavailable.
 - Cannot complete operation because VMware Tools is not running in this virtual machine.
```

Tests Run : 
`(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vapp_vm.TestVAppVM.test_1004_shutdown_vapp
.
----------------------------------------------------------------------
Ran 1 test in 14.628s

OK
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vapp_vm.TestVAppVM.test_1005_reboot_vapp
.
----------------------------------------------------------------------
Ran 1 test in 10.343s

OK

`
`(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vm.TestVM.test_1005_reboot_vm
.
----------------------------------------------------------------------
Ran 1 test in 6.778s

OK
(pyvcloud) malakars-m01:tests malakars$ python -m unittest vcd_vm.TestVM.test_1004_shutdown_vm
.
----------------------------------------------------------------------
Ran 1 test in 8.307s

OK
`
- @rocknes @pacogomez @anusuyar @sahithi @hodgesrm @rdbwebster

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/172)

### CODE REVIEW

**Comment by sahithi** [comment]
:lgtm: after addressing the comment.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/vapp.py, line 652 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-L3VQeGbpxvIJISyNfgO:-L3VQeGbpxvIJISyNfgP:bq181sa) ([raw file](https://github.com/vmware/vcd-cli/blob/0c59775587e747091b9a03e72b180afbf1cf7e6b/vcd_cli/vapp.py#L652)):*
> ```Python
>     callback=abort_if_false,
>     expose_value=False,
>     prompt='Are you sure you want to shutdown the vApp?')
> ```

Are you sure you want to shutdown the vApp or VM(s)?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-:-L3VRJTJB0d2NAJ0eAIr:b-3tyijn)*

**Comment by sahithi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/vapp.py, line 119 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-L3VaIKmN6kN5w1i8df5:-L3VaIKmN6kN5w1i8df6:b-8erxbu) ([raw file](https://github.com/vmware/vcd-cli/blob/0c59775587e747091b9a03e72b180afbf1cf7e6b/vcd_cli/vapp.py#L119)):*
> ```Python
>             Delete vm1 and vm2 from vapp1.
> \b
>         vcd vapp reboot vapp1 vm1 --yes
> ```

I think it is better to give more than one vm to demonstrate that multiple vms can be passed as options

 vcd vapp reboot vapp1 vm1 vm2 --yes
Reboot 1 or more vms in Vapp

---

*[vcd_cli/vapp.py, line 123 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-L3VacNp1PcBxxxv14Rk:-L3VacNp1PcBxxxv14Rl:blf2cgt) ([raw file](https://github.com/vmware/vcd-cli/blob/0c59775587e747091b9a03e72b180afbf1cf7e6b/vcd_cli/vapp.py#L123)):*
> ```Python
> \b
>         vcd vapp shutdown vapp1 vm1 --yes
>             Shutdown vm1 in vApp.
> ```

Similar to above comment.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172)*

**Comment by sompa** [comment]
*[vcd_cli/vapp.py, line 652 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-L3VQeGbpxvIJISyNfgO:-L3WfpNrIVD16sG8R4u1:bppg9cj) ([raw file](https://github.com/vmware/vcd-cli/blob/0c59775587e747091b9a03e72b180afbf1cf7e6b/vcd_cli/vapp.py#L652)):*
> or VM(s)
Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172)*

**Comment by sompa** [comment]
*[vcd_cli/vapp.py, line 119 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-L3VaIKmN6kN5w1i8df5:-L3Wg9X_oy1yC9e9go0I:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/0c59775587e747091b9a03e72b180afbf1cf7e6b/vcd_cli/vapp.py#L119)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

I think it is better to give more than one vm to demonstrate that multiple vms can be passed as options

 vcd vapp reboot vapp1 vm1 vm2 --yes
Reboot 1 or more vms in Vapp
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172)*

**Comment by sompa** [comment]
*[vcd_cli/vapp.py, line 123 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-L3VacNp1PcBxxxv14Rk:-L3WgB_Q5y5iDfbJfi0m:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/0c59775587e747091b9a03e72b180afbf1cf7e6b/vcd_cli/vapp.py#L123)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Similar to above comment.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172)*

**Comment by sompa** [comment]
Done.

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-:-L3WgiaRuw0tySUoTu0P:b-896fix)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-:-L3ZtOXVZjrEningI0wT:bnfp4nl)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/172#-:-L3ZwIYkL2W_iQnHbEsT:bnfp4nl)*

**Pull request merged**
