### PR TITLE
VCDA-451: work with pending tasks

### PR DESCRIPTION
**Pull request by pacogomez**
- fixes --no-wait option
- list tasks by status
- wait for task by id
- process MissingRecordException

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/167)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 4 of 4 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/task.py, line 82 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/167#-L3EkUea-ruXuFq34Cjt:-L3EkUeboFWUlDfWuvJH:b1jnkor) ([raw file](https://github.com/vmware/vcd-cli/blob/0806074227a862f99517052108a829b7013481af/vcd_cli/task.py#L82)):*
> ```Python
>         client = ctx.obj['client']
>         task_obj = Task(client)
>         records = task_obj.list_tasks(filter_statuses=status)
> ```

filter_status_list sounds better than filter_statuses.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/167)*

**Comment by sahithi** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/167#-:-L3El-VGyjOIaTgPY6CQ:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/task.py, line 82 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/167#-L3EkUea-ruXuFq34Cjt:-L3Ez4eKmgO2lRT0TU4k:b-cu5w1j) ([raw file](https://github.com/vmware/vcd-cli/blob/0806074227a862f99517052108a829b7013481af/vcd_cli/task.py#L82)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

filter_status_list sounds better than filter_statuses.
</blockquote></details>

I will change it

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/167)*

**Comment by pacogomez** [comment]
Review status: 3 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/task.py, line 82 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/167#-L3EkUea-ruXuFq34Cjt:-L3F40BVNleWo9alC8E3:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/0806074227a862f99517052108a829b7013481af/vcd_cli/task.py#L82)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I will change it
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/167)*

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/167#-:-L3FHS7H14TcuYVAB6oi:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 3 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/167)*

**Pull request merged**
