### PR TITLE
added wait for async commands to complete (attach vc and create pvdc)

### PR DESCRIPTION
**Pull request by ckolovson**
- added wait for async commands to complete (attach vc and create pvdc)

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/208)

### CODE REVIEW

**Comment by rocknes** [comment]
:lgtm:

This review was not showing up on reviewable.io, I had to manually add it.  Did you paste the reviewable.io link on our review channel?

---

Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---

*[vcd_cli/pvdc.py, line 150 at r1](https://beta.reviewable.io/reviews/vmware/vcd-cli/208#-L99U-Q27QVzE7LnEq7Q:-L99U-Q27QVzE7LnEq7R:b-4x58yh) ([raw file](https://github.com/vmware/vcd-cli/blob/badf9e8fee7d4480760a2016f4a06e4ccc84d5a2/vcd_cli/pvdc.py#L150)):*
> ```Python
>                                      is_enabled=enable,
>                                      description=description,
>                                      highest_supp_hw_vers=highest_supp_hw_vers,
> ```

Please make sure that the other pull request which shortened the variable name is merged before you merge this pull request.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/208#-:-L99UEbK82j7qZOqE7_f:b-vr1wc3)*

**Comment by hodgesrm** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/208#-:-L9facMC3uTSnLA2C8EG:bnfp4nl)*

**Comment by hodgesrm** [comment]
Reviewed 2 of 2 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/208)*

**Comment by ckolovson** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/pvdc.py, line 150 at r1](https://beta.reviewable.io/reviews/vmware/vcd-cli/208#-L99U-Q27QVzE7LnEq7Q:-L9fah9uE4tQQO8eOHax:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/badf9e8fee7d4480760a2016f4a06e4ccc84d5a2/vcd_cli/pvdc.py#L150)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Please make sure that the other pull request which shortened the variable name is merged before you merge this pull request.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/208)*

**Pull request merged**
