### PR TITLE
 VCDA-477: Add doc for logging request headers and payload for debugging purposes

### PR DESCRIPTION
**Pull request by sompa**
This includes a short description of how to enable logging of request headers and payload for help with debugging, in the contributing guide. 

-  Add doc for logging request headers and payload for debugging purposes

- Changes to the contributing guide for vcd-cli to enable logging of request headers and payloads.

- @sahithi @hodgesrm @anusuyar @pacogomez @ckolovson

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/191)

### CODE REVIEW

**Comment by hodgesrm** [comment]
:lgtm:

(See note on capitalization of OS types.)

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[CONTRIBUTING.md, line 56 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/191#-L5GW0dYyZfJ45vHATIJ:-L5GW0dYyZfJ45vHATIK:bvzfn3k) ([raw file](https://github.com/vmware/vcd-cli/blob/5eca5f26d41fb8460283e61e9243122f2b32abd2/CONTRIBUTING.md#L56)):*
> ```Markdown
> 
> ### Debugging
> In order to help with debugging the code better, we have included a profiles.yaml file. This is located under ~/.vcd-cli/profiles.yaml (for mac,linux and windows users). You can turn on logging of request body, header or the entire payload
> ```

Suggest capitalizing OS types to match other documentation references: Mac OS X, Linux, and Windows

Once this is fixed it's good to go. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/191#-:-L5GWJwG4MLFls3_tDj4:b-cqvemk)*

**Comment by sahithi** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 56 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/191#-L5KWwyhMB86Qmdw53p3:-L5KWwyhMB86Qmdw53p4:b-1v7f4g) ([raw file](https://github.com/vmware/vcd-cli/blob/5eca5f26d41fb8460283e61e9243122f2b32abd2/CONTRIBUTING.md#L56)):*
> ```Markdown
> 
> ### Debugging
> In order to help with debugging the code better, we have included a profiles.yaml file. This is located under ~/.vcd-cli/profiles.yaml (for mac,linux and windows users). You can turn on logging of request body, header or the entire payload
> ```

The main purpose of profiles.yaml is to maintain the user+vCD context Not Debugging. Please rephrase the first line accordingly.

For windows ->%USERPROFILE%\.vcd-cli\profiles.yaml @anusuyar ; Windows does not have HOME environment variable set by default. It is USERPROFILE by default. I also doubt if '~/.' works in windows.

Also, I suggest to mention an example for clarity:

active: default
profiles:
- api_version: '30.0'
  disable_warnings: false
  host: cassini.eng.vmware.com
  log_body: true
  log_header: true
  log_request: true

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/191)*

**Comment by sompa** [comment]
Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---

*[CONTRIBUTING.md, line 56 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/191#-L5KWwyhMB86Qmdw53p3:-L5KrqpajllryPMfPo86:b-kgq3fb) ([raw file](https://github.com/vmware/vcd-cli/blob/5eca5f26d41fb8460283e61e9243122f2b32abd2/CONTRIBUTING.md#L56)):*
> active: default
> profiles:
> 
> api_version: '30.0'
> disable_warnings: false
> host: cassini.eng.vmware.com
> log_body: true
> log_header: true
> log_request: true

Done. 

---

*[CONTRIBUTING.md, line 56 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/191#-L5GW0dYyZfJ45vHATIJ:-L5Krtps7bkWtG-rSAlX:bs7wumx) ([raw file](https://github.com/vmware/vcd-cli/blob/5eca5f26d41fb8460283e61e9243122f2b32abd2/CONTRIBUTING.md#L56)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Suggest capitalizing OS types to match other documentation references: Mac OS X, Linux, and Windows

Once this is fixed it's good to go. 
</blockquote></details>

Done. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/191)*

**Comment by sahithi** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/191#-:-L5LM8w7EGo--42_x7gn:bnfp4nl)*

**Pull request merged**
