### PR TITLE
VCDA-362,343,408 Power-off, undeploy, delete VM(s)

### PR DESCRIPTION
**Pull request by pacogomez**
To help us process your pull request efficiently, please include: 

- (Required) Short description of changes in the PR topic line
  - power-off, undeploy, delete VM(s)
  - minor PEP8 compliance changes
  - documentation improvements
  - new documentation not generated yet
  - vapp examples:
```
        vcd vapp power-off vapp1 vm1 vm2
            Power off vm1 and vm2 of vapp1.
        vcd vapp undeploy vapp1 vm1 vm2
            Undeploy vm1 and vm2 of vapp1.
        vcd vapp delete vapp1 vm1 vm2
            Delete vm1 and vm2 from vapp1.
```

- (Required) Detailed description of changes include tests and
  documentation.  If the pull request contains multiple commits with 
  detailed messages, refer to those instead
see commit messages

- (Optional) Names of reviewers using @ sign + name
@rocknes @sahithi @anusuyar @sompa

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/155)

### CODE REVIEW

**Comment by sahithi** [comment]
Reviewed 11 of 11 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/vapp.py, line 399 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L22kOC7vH83REanCQjx:-L22kOC8AszNYIGFIjXK:b7i8r3d) ([raw file](https://github.com/vmware/vcd-cli/blob/d6f68980f4bafe31c56857a5b650b9d1b91a10b1/vcd_cli/vapp.py#L399)):*
> ```Python
>             vapp = VApp(client, resource=vapp_resource)
>             task = vapp.delete_vms(vm_names)
>             stdout(task, ctx)
> ```

Get the stdout(task, ctx) out of if-else block.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[vcd_cli/vapp.py, line 399 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L22kOC7vH83REanCQjx:-L237B7nVyDNCApefPJC:b-d7bhn0) ([raw file](https://github.com/vmware/vcd-cli/blob/d6f68980f4bafe31c56857a5b650b9d1b91a10b1/vcd_cli/vapp.py#L399)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Get the stdout(task, ctx) out of if-else block.
</blockquote></details>

will do

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by rocknes** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 537 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L24YTKvYjtfBhajwmKA:-L24YTKvYjtfBhajwmKB:b-xctuy) ([raw file](https://github.com/vmware/vcd-cli/blob/cc47065756497e180148de01a879df579a212869/vcd_cli/vapp.py#L537)):*
> ```Python
> @click.argument('vm-names',
>                 nargs=-1)
> def power_on(ctx, name, vm_names):
> ```

It looks like we are not using the vm_names param

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 537 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L24YTKvYjtfBhajwmKA:-L25z9lT9mcZcDyGREVR:b-73nukz) ([raw file](https://github.com/vmware/vcd-cli/blob/cc47065756497e180148de01a879df579a212869/vcd_cli/vapp.py#L537)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

It looks like we are not using the vm_names param
</blockquote></details>

will remove

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 537 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L24YTKvYjtfBhajwmKA:-L25zuEtIv-40QazsVgW:b-dxsao7) ([raw file](https://github.com/vmware/vcd-cli/blob/cc47065756497e180148de01a879df579a212869/vcd_cli/vapp.py#L537)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

will remove
</blockquote></details>

better yet, I'm adding the `vm.power_on` option

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by anusuyar** [comment]
Reviewed 9 of 11 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by rocknes** [comment]
:lgtm:

---

Reviewed 9 of 11 files at r1, 2 of 2 files at r3.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[tox.ini, line 2 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2C0gM6iHjn1ASLl0pV:-L2C0gM6iHjn1ASLl0pW:bva93mj) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/tox.ini#L2)):*
> ```INI
> [flake8]
> import-order-style = smarkets
> ```

Should we make this google style?

---

*[vcd_cli/vapp.py, line 399 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L22kOC7vH83REanCQjx:-L2CEgO7cV-r0OdyHNqF:b-w4pyo9) ([raw file](https://github.com/vmware/vcd-cli/blob/d6f68980f4bafe31c56857a5b650b9d1b91a10b1/vcd_cli/vapp.py#L399)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

will do
</blockquote></details>

Does python have block level scope for variables? If yes then task inside the if-else block would be different from the task that is being printed out.

Also, shouldn't the force param be sent to delete_vms function?

---

*[vcd_cli/vapp.py, line 376 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CEFM_SzSlDykNHKsx:-L2CEFM_SzSlDykNHKsy:b7nnaq) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L376)):*
> ```Python
> @vapp.command(short_help='delete a vApp or VM(s)')
> @click.pass_context
> @click.argument('name',
> ```

without metavar the help will show name all in capitals.

---

*[vcd_cli/vapp.py, line 486 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CHc0_zpA_ZTkRRcRB:-L2CHc0_zpA_ZTkRRcRC:bqxi3wn) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L486)):*
> ```Python
>             for vm_name in vm_names:
>                 vm = VM(client, resource=vapp.get_vm(vm_name))
>                 task = vm.power_off()
> ```

We are not using the force param

---

*[vcd_cli/vapp.py, line 514 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CGtMTY4mtUkNc9uQY:-L2CGtMTY4mtUkNc9uQZ:b61m9ej) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L514)):*
> ```Python
>               default='default',
>               help='Undeploy power action')
> def undeploy(ctx, name, vm_names, force, action):
> ```

How are we using the force param? shouldn't we be sending it to vapp.deploy/vm.undeploy ?

---

*[vcd_cli/vapp.py, line 562 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CHzZry0J1u6K7T_jM:-L2CHzZry0J1u6K7T_jN:b-5hh0sb) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L562)):*
> ```Python
> @vapp.command('shutdown', short_help='shutdown a vApp')
> @click.pass_context
> @click.argument('name',
> ```

Removing the metavar will cause name to appear in all capitals in help section.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-:-L2CI8uqhAhHeKozOH_N:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: 4 of 11 files reviewed at latest revision, 6 unresolved discussions.

---

*[tox.ini, line 2 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2C0gM6iHjn1ASLl0pV:-L2OriNNuF33PTdmr9yi:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/tox.ini#L2)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Should we make this google style?
</blockquote></details>

Done.

---

*[vcd_cli/vapp.py, line 399 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L22kOC7vH83REanCQjx:-L2OsfvNsysQ3nqqD4dA:bcecocs) ([raw file](https://github.com/vmware/vcd-cli/blob/d6f68980f4bafe31c56857a5b650b9d1b91a10b1/vcd_cli/vapp.py#L399)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Does python have block level scope for variables? If yes then task inside the if-else block would be different from the task that is being printed out.

Also, shouldn't the force param be sent to delete_vms function?
</blockquote></details>

Python doesn't have block level variable scope.

The semantics are a bit different for the `force` param if it is a vApp or VMs. Force in this command only applies to deleting a vApp. I will make it clear in the help.

---

*[vcd_cli/vapp.py, line 376 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CEFM_SzSlDykNHKsx:-L2OsHcoVl-cmbShEPaq:b-soz3i7) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L376)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

without metavar the help will show name all in capitals.
</blockquote></details>

for now I will leave the default metavar until we agree on a consistent alternative

---

*[vcd_cli/vapp.py, line 486 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CHc0_zpA_ZTkRRcRB:-L2OvD6MpZQUJCaNJXfA:b-hfpv0l) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L486)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We are not using the force param
</blockquote></details>

removed

---

*[vcd_cli/vapp.py, line 514 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CGtMTY4mtUkNc9uQY:-L2OvQooLu-zG5iLQ91a:bcyj5n6) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L514)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

How are we using the force param? shouldn't we be sending it to vapp.deploy/vm.undeploy ?
</blockquote></details>

not being used in this version of the command

---

*[vcd_cli/vapp.py, line 562 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CHzZry0J1u6K7T_jM:-L2OvVH7p2HiA0PEI8gB:bqsr0j4) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L562)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

Removing the metavar will cause name to appear in all capitals in help section.
</blockquote></details>

we need to follow up on this topic

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by rocknes** [comment]
Reviewed 7 of 7 files at r4.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 514 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CGtMTY4mtUkNc9uQY:-L2PItuaTkSWNiz_rApj:b-yvm5ci) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L514)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

not being used in this version of the command
</blockquote></details>

If we are not using the option, probably we should get rid of it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 514 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CGtMTY4mtUkNc9uQY:-L2QL-FfgwmwbaRcmGGg:b-2kqorr) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L514)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

If we are not using the option, probably we should get rid of it.
</blockquote></details>

yes, I'm removing it and will add it in the future when we implement it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Comment by pacogomez** [comment]
Review status: 10 of 11 files reviewed at latest revision, 2 unresolved discussions.

---

*[vcd_cli/vapp.py, line 514 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/155#-L2CGtMTY4mtUkNc9uQY:-L2QMj1t0QqHzWBXEON9:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/76354841d8645ecd07184ccdb5100e9525a3042a/vcd_cli/vapp.py#L514)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

yes, I'm removing it and will add it in the future when we implement it.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/155)*

**Pull request merged**
