### PR TITLE
VDP-1205, VCDA-462: added create PVDC to pvdc.py

### PR DESCRIPTION
**Pull request by ckolovson**
Added create PVDC
Reviewers: @pacogomez @sahithi @anusuyar

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/182)

### CODE REVIEW

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 18 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5Ascl2tOMl6WYAQA9K:-L5Ascl2tOMl6WYAQA9L:bpaf1y6) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L18)):*
> ```Python
> from pyvcloud.vcd.pvdc import PVDC
> from pyvcloud.vcd.system import System
> from pyvcloud.vcd.platform import Platform
> ```

import order should be alphabetical.

---

*[vcd_cli/pvdc.py, line 41 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AtdwTXUPNRhV8_pWC:-L5AtTGRjoxOUY74JJgo:bgchfk2) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L41)):*
> ```Python
> \b
>         vcd pvdc create pvdc-name vc-name 
>             --storage-profile 'SP name' (required, can be multiple)
> ```

better to avoid explanations in the brackets. It should go in the description.

---

*[vcd_cli/pvdc.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AtuDwfLP6Ng_ZyJ09:-L5AtuDwfLP6Ng_ZyJ0A:bfuzcx2) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L44)):*
> 'HighestSupportedHardwareVersion'

What are the possible values of   --highest-supported-hw-version ? If there are only fixed accepted values, they should be added in click.Choice  like below

type=click.Choice(['ReadOnly', 'Change', 'FullControl']) 

---

*[vcd_cli/pvdc.py, line 96 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AuaQDVbqZFMIMiQWo:-L5AuaQEg0w2_M2XVZHj:bua1as3) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L96)):*
> ```Python
>     required=True,
>     default=None,
>     multiple=True,
> ```

help should be added for each option

---

*[vcd_cli/pvdc.py, line 131 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AsreHsvAfShSkwerr:-L5AsreHsvAfShSkwers:b-wyooku) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L131)):*
> ```Python
>         client = ctx.obj['client']
>         platform = Platform(client)
>         pvdc = platform.create_provider_vdc(vc_name, 
> ```

for a long argument list, it's better to pass arguments with name and value. eg 

 platform.create_provider_vdc(name=vc_name,resource_poll= resource_pool, sp=storage_profile, pvdc_name = pvdc_name, enable,)

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by sompa** [comment]
*[vcd_cli/pvdc.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5B-IUB49n46CpZkYxm:-L5B-IUB49n46CpZkYxn:b-cofrfu) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L46)):*
> ```Python
>             --highest-supported-hw-version 'HighestSupportedHardwareVersion' 
>             --description 'description' --enable 
>                 Create Provider Virtual Datacenter
> ```

Is the --enable flag required in this example ? If so, please add notes to explain what it does ?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by ckolovson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 6 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 18 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5Ascl2tOMl6WYAQA9K:-L5EkIRzRN806pNR9RQX:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L18)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

import order should be alphabetical.
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 41 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AtdwTXUPNRhV8_pWC:-L5Ep8TEGVHWlXAVG8sW:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L41)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

better to avoid explanations in the brackets. It should go in the description.
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AtuDwfLP6Ng_ZyJ09:-L5EqEUUTZpBODBQaazx:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L44)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

> 'HighestSupportedHardwareVersion'

What are the possible values of   --highest-supported-hw-version ? If there are only fixed accepted values, they should be added in click.Choice  like below

type=click.Choice(['ReadOnly', 'Change', 'FullControl']) 
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 46 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5B-IUB49n46CpZkYxm:-L5EqQkTztmdqRLgbYyw:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L46)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

Is the --enable flag required in this example ? If so, please add notes to explain what it does ?
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 96 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AuaQDVbqZFMIMiQWo:-L5EqSVU3YsdYAXedyq0:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L96)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

help should be added for each option
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 131 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AsreHsvAfShSkwerr:-L5ExkwNnQnBCjDuIcKn:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L131)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

for a long argument list, it's better to pass arguments with name and value. eg 

 platform.create_provider_vdc(name=vc_name,resource_poll= resource_pool, sp=storage_profile, pvdc_name = pvdc_name, enable,)
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by sompa** [comment]
*[vcd_cli/pvdc.py, line 147 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5GBfPGb-4vr8bPtmL1:-L5GBfPGb-4vr8bPtmL2:b-3d6f5b) ([raw file](https://github.com/vmware/vcd-cli/blob/0c519dd3f12f2f8ad7b45618d8aae794ae3bf7e8/vcd_cli/pvdc.py#L147)):*
> ```Python
>                                      is_enabled=enable,
>                                      description=description,
>                                      highest_supp_hw_vers=highest_supported_hw_version,  # NoQA
> ```

#NoQA is not required here. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by sompa** [comment]
*[vcd_cli/pvdc.py, line 149 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5GBpTex8x_7i3zpf4E:-L5GBpTex8x_7i3zpf4F:bk148az) ([raw file](https://github.com/vmware/vcd-cli/blob/0c519dd3f12f2f8ad7b45618d8aae794ae3bf7e8/vcd_cli/pvdc.py#L149)):*
> ```Python
>                                      highest_supp_hw_vers=highest_supported_hw_version,  # NoQA
>                                      vxlan_network_pool=vxlan_network_pool)
>         stdout('PVDC create successful', ctx)
> ```

nit: PVDC creation successful or PVDC created successfully.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by ckolovson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 147 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5GBfPGb-4vr8bPtmL1:-L5GEEGa781nX99ucZUF:bw96twp) ([raw file](https://github.com/vmware/vcd-cli/blob/0c519dd3f12f2f8ad7b45618d8aae794ae3bf7e8/vcd_cli/pvdc.py#L147)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

#NoQA is not required here. 
</blockquote></details>

But without it I get a flake8 error. I removed it in any case. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by ckolovson** [comment]
Review status: 0 of 1 files reviewed at latest revision, 8 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 147 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5GBfPGb-4vr8bPtmL1:-L5GEM7uIJm3XeJRi7R3:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/0c519dd3f12f2f8ad7b45618d8aae794ae3bf7e8/vcd_cli/pvdc.py#L147)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

But without it I get a flake8 error. I removed it in any case. 
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 149 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5GBpTex8x_7i3zpf4E:-L5GEMmrV77QvE0-qmGL:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/0c519dd3f12f2f8ad7b45618d8aae794ae3bf7e8/vcd_cli/pvdc.py#L149)):*
<details><summary><i>Previously, sompa (malakars) wrote…</i></summary><blockquote>

nit: PVDC creation successful or PVDC created successfully.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by anusuyar** [comment]
Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 128 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5HHmWXOhZpOVHe6okF:-L5HHmWXOhZpOVHe6okG:b13hi8b) ([raw file](https://github.com/vmware/vcd-cli/blob/0b2699fd129dac8ab12aee98b4459a84fe79c256/vcd_cli/pvdc.py#L128)):*
> ```Python
> @click.option(
>     '--highest-supported-hw-version',
>     type=click.Choice(['vmx-4', 'vmx-7', 'vmx-9', 'vmx-10', 'vmx-11', 'vmx-12',
> ```

these are the only possible values of this option?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by ckolovson** [comment]
Yes, according to JB Niviot. He said that new versions may be introduced with new versions of ESX.

**Comment by anusuyar** [comment]
Please post the following outputs after making the changes.

vcd pvdc -h
vcd pvdc create -h

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AtuDwfLP6Ng_ZyJ09:-L5AtsQhYhISHcEjihAt:b-573cfk) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L44)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

If are removing click.Choice() from this option, we can change the example as below.

 --highest-supported-hw-version vmx-11

This gives the user an idea of what kind of values to pass for hardware version. They can get the value by invoking the list hardware-version command

---

*[vcd_cli/pvdc.py, line 128 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5HHmWXOhZpOVHe6okF:-L5HJi27UEIWnqbnATqC:bz4wzl1) ([raw file](https://github.com/vmware/vcd-cli/blob/0b2699fd129dac8ab12aee98b4459a84fe79c256/vcd_cli/pvdc.py#L128)):*
<details><summary><i>Previously, ckolovson (Curt Kolovson) wrote…</i></summary><blockquote>

That’s what I was told. 
</blockquote></details>

since we will have more versions added in the future release, we should avoid having a fixed list of values here.  (otherwise, we  need to update this list for each new VCD release). I am fine reverting back to the previous implementation.

since the user will not know what values to use here, we need to create another cli command to list all hardware versions. The user can use the value in that list to create pvdc. We can have this command as a separate task.

---

*[vcd_cli/pvdc.py, line 42 at r4](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5Ky8YVaIUARiVSSAp6:-L5Ky8YWEJYZIbOuAz26:b1l0mxe) ([raw file](https://github.com/vmware/vcd-cli/blob/dc10475989d4ff0e41c30957d2fb9e1591a748ae/vcd_cli/pvdc.py#L42)):*
> ```Python
>         vcd pvdc create pvdc-name vc-name
>             --storage-profile 'SP name'
>             --resource-pool 'RP name'
> ```

Consider having the names of the resource as follows if it makes more sense.

```
 vcd pvdc create pvdc-name vc-name
            --storage-profile '*' 
             --storage-profile 'sp1' 
            --resource-pool 'rp1'
            --resource-pool 'rp2'
            --vxlan-network-pool 'vnp1'
            --highest-supported-hw-version vmx-11
            --description 'description'
            --enable
```

Having multiple values in the examples will give users idea about how to pass multiple values.(for sp and rp in our case)

---

*[vcd_cli/pvdc.py, line 93 at r4](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5KtDdW2xBCIW94lddZ:-L5KtDdW2xBCIW94ldd_:b-nzetv2) ([raw file](https://github.com/vmware/vcd-cli/blob/dc10475989d4ff0e41c30957d2fb9e1591a748ae/vcd_cli/pvdc.py#L93)):*
> ```Python
> @click.argument('pvdc-name', metavar='<pvdc-name>', required=True)
> @click.argument('vc-name', metavar='<vc-name>', required=True)
> @click.option(
> ```

Since all the option name is very long for this command, try adding a short form for each option if it makes sense. 

storage-profile --> s
resource-pool --> r
vxlan-network-pool -> n
--highest-supported-hw-version -> v

---

*[vcd_cli/pvdc.py, line 105 at r4](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5KzhtJ0NDZci2FCS3s:-L5KzhtJ0NDZci2FCS3t:b-1c3xkw) ([raw file](https://github.com/vmware/vcd-cli/blob/dc10475989d4ff0e41c30957d2fb9e1591a748ae/vcd_cli/pvdc.py#L105)):*
> ```Python
>     default=None,
>     multiple=True,
>     metavar='[resource-pool]',
> ```

Remove metavar for options with multiple values. This will allow click to show that this option can accept more than 1 variable automatically in help.

Do this for storage-profile too.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-:-L5L-pXQ9gJHdaS-Po-t:b-pwi6x2)*

**Comment by ckolovson** [comment]
> vcd pvdc -h
$ vcd pvdc -h
Usage: vcd pvdc [OPTIONS] COMMAND [ARGS]...

  Work with provider virtual datacenters in vCloud Director.

      Examples
          vcd pvdc list
              Get list of provider virtual datacenters.
  
          vcd pvdc info name
              Display provider virtual data center details.
  
          vcd pvdc create pvdc-name vc-name
              --storage-profile 'sp1'
              --storage-profile 'sp2'
              --resource-pool 'rp1'
              --resource-pool 'rp2'
              --vxlan-network-pool 'vnp1'
              --highest-supported-hw-version 'vmx-11'
              --description 'description'
              --enable
                  Create Provider Virtual Datacenter.
                     Parameters --storage-profile and --resource-pool are both
                     required parameters and each can have multiple entries.
      

Options:
  -h, --help  Show this message and exit.

Commands:
  create  create pvdc
  info    show pvdc details
  list    list of provider virtual datacenters
---
$ vcd pvdc create -h
Usage: vcd pvdc create [OPTIONS] <pvdc-name> <vc-name>

Options:
  -s, --storage-profile TEXT      storage profile name (required parameter,
                                  can have multiple)  [required]
  -r, --resource-pool TEXT        resource pool name (required parameter, can
                                  have multiple)  [required]
  -n, --vxlan-network-pool [vxlan-network-pool]
                                  vxlan network pool name
  -d, --description [description]
                                  description of PVDC
  -e, --enable                    enable flag (enables PVDC when it is
                                  created)
  -v, --highest-supported-hw-version [highest-supported-hw-version]
                                  highest supported hardware version, e.g.
                                  vmx-11, vmx-10, vmx-09, etc.
  -h, --help                      Show this message and exit.
(vcd-cli) ckolovson-m01:vcd-cli ckolovson$ 

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[vcd_cli/pvdc.py, line 44 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5AtuDwfLP6Ng_ZyJ09:-L5LoC-wwkHfG_0eRbQu:bx7q1m) ([raw file](https://github.com/vmware/vcd-cli/blob/a5393845b9f9c74dc6137c5df55a5d8d6d97fc92/vcd_cli/pvdc.py#L44)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

If are removing click.Choice() from this option, we can change the example as below.

 --highest-supported-hw-version vmx-11

This gives the user an idea of what kind of values to pass for hardware version. They can get the value by invoking the list hardware-version command

</blockquote></details>

The actual valid versions depend on the hosts backing the RP (the highest supported is the lowest common denominator accross all hosts in the cluster). 

---

*[vcd_cli/pvdc.py, line 42 at r4](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5Ky8YVaIUARiVSSAp6:-L5LnrJp1x2lc7o0wgBp:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/dc10475989d4ff0e41c30957d2fb9e1591a748ae/vcd_cli/pvdc.py#L42)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Consider having the names of the resource as follows if it makes more sense.

```
 vcd pvdc create pvdc-name vc-name
            --storage-profile '*' 
             --storage-profile 'sp1' 
            --resource-pool 'rp1'
            --resource-pool 'rp2'
            --vxlan-network-pool 'vnp1'
            --highest-supported-hw-version vmx-11
            --description 'description'
            --enable
```

Having multiple values in the examples will give users idea about how to pass multiple values.(for sp and rp in our case)
</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 93 at r4](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5KtDdW2xBCIW94lddZ:-L5Lp2iNsdDl07jmfH2F:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/dc10475989d4ff0e41c30957d2fb9e1591a748ae/vcd_cli/pvdc.py#L93)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Since all the option name is very long for this command, try adding a short form for each option if it makes sense. 

storage-profile --> s
resource-pool --> r
vxlan-network-pool -> n
--highest-supported-hw-version -> v

</blockquote></details>

Done.

---

*[vcd_cli/pvdc.py, line 105 at r4](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-L5KzhtJ0NDZci2FCS3s:-L5LpD-dULT9fPaY_IjN:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/dc10475989d4ff0e41c30957d2fb9e1591a748ae/vcd_cli/pvdc.py#L105)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Remove metavar for options with multiple values. This will allow click to show that this option can accept more than 1 variable automatically in help.

Do this for storage-profile too.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-:-L5Lq0FuO9Cc7KjyxF8S:b-qlw0uw)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-:-L5LrppdKtNLLWO0UaBe:bnfp4nl)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r5.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182)*

**Comment by sompa** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r2.
Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/182#-:-L5PwnDhI3-DGEGSAhVA:bnfp4nl)*

**Pull request merged**
