### PR TITLE
VCDA517: Document generation for all commands

### PR DESCRIPTION
**Pull request by sahithi**
Document generation for all commands

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/195)

### CODE REVIEW

**Comment by hodgesrm** [comment]
Do we make it clear somewhere that you have to pip3 install the cse code to get cse commands?  Posting these docs to vcd-cli makes it seem as if it's embedded.  

This seems potentially confusing. 

---

Review status: 0 of 37 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/195#-:-L6sRLBy1jOuPyXbBuNH:bpu7m28)*

**Comment by sompa** [comment]
:lgtm:

---

Reviewed 37 of 37 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/195#-:-L6wrT0a08s98ud1RcCm:bnfp4nl)*

**Comment by sahithi** [comment]
Robert, you are right. We do need to mention that CSE installation is necessary before trying out CSE commands. Where do you suggest we add that?

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://beta.reviewable.io/reviews/vmware/vcd-cli/195#-:-L70m_j41arohpXdzw_3:boj2leu)*

**Comment by hodgesrm** [comment]
:lgtm:

Let's go with your fix for now.  We'll need to sort this out later but in the meantime users have good documentation.  

---

Reviewed 37 of 37 files at r1.
Review status: 37 of 38 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/195#-:-L716u-2iL8qmx1GdkXa:bynpql9)*

**Comment by hodgesrm** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/195)*

**Pull request merged**
