### PR TITLE
VCDA-381/2/3/4/5

### PR DESCRIPTION
**Pull request by pacogomez**
- method to add external commands
- externalized cluster command and moved it to CSE project
- added example customization shell script
- tasks now print and leave the intermediate state in its own line
- list VMs in a vapp with the vapp list command
- re-generated documentation

@rocknes @sahithi @anusuyar

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/150)

### CODE REVIEW

**Comment by anusuyar** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150)*

**Comment by anusuyar** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-:-L1KRNmdO-h4AFes5rwQ:bnfp4nl)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, all commit checks successful.

---

*[vcd_cli/vapp.py, line 214 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1KSiBios16tBvcHHQE:-L1KSiBios16tBvcHHQF:b-725ze5) ([raw file](https://github.com/vmware/vcd-cli/blob/d0d541687a308b5cdeda4d931ebc31469daed1eb/vcd_cli/vapp.py#L214)):*
> ```Python
> 
> 
> @vapp.command('list', short_help='list vApps')
> ```

please add usage example.

---

*[vcd_cli/vapp.py, line 219 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1KQGzeoW7YqsF_dc6r:-L1KQGzeoW7YqsF_dc6s:b58d82i) ([raw file](https://github.com/vmware/vcd-cli/blob/d0d541687a308b5cdeda4d931ebc31469daed1eb/vcd_cli/vapp.py#L219)):*
Is command
>vcd vapp info myVapp
give similar result as
>vcd vapp list myVapp
?
If yes, any reason we why are re-implementing?

---

*[vcd_cli/vapp.py, line 228 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1KSMiPD9xXxsDpdaQT:-L1KSMiPD9xXxsDpdaQU:b-5hwm8q) ([raw file](https://github.com/vmware/vcd-cli/blob/d0d541687a308b5cdeda4d931ebc31469daed1eb/vcd_cli/vapp.py#L228)):*
> ```Python
>             attributes = None
>         else:
>             resource_type = 'adminVm' if is_sysadmin(ctx) else 'vm'
> ```

Am I missing something here? Why is vapp command taking vm name as parameter (resource_type='vm')

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150)*

**Comment by sahithi** [comment]
Reviewed 21 of 21 files at r1.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150)*

**Comment by pacogomez** [comment]
Review status: 19 of 21 files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/vapp.py, line 214 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1KSiBios16tBvcHHQE:-L1L8TyW_OAmYxN5YKax:btdv34e) ([raw file](https://github.com/vmware/vcd-cli/blob/d0d541687a308b5cdeda4d931ebc31469daed1eb/vcd_cli/vapp.py#L214)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

please add usage example.
</blockquote></details>

I will

---

*[vcd_cli/vapp.py, line 219 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1KQGzeoW7YqsF_dc6r:-L1L8DyuZTIh8B85MTf2:b-gun428) ([raw file](https://github.com/vmware/vcd-cli/blob/d0d541687a308b5cdeda4d931ebc31469daed1eb/vcd_cli/vapp.py#L219)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Is command
>vcd vapp info myVapp
give similar result as
>vcd vapp list myVapp
?
If yes, any reason we why are re-implementing?

</blockquote></details>

`vcd vapp list myVapp` lists the vApp VMs, like `vcd catalog list mycatalog` lists the catalog items

---

*[vcd_cli/vapp.py, line 228 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1KSMiPD9xXxsDpdaQT:-L1L8RoAqPZ2PD4RTOhq:b-lxwe1y) ([raw file](https://github.com/vmware/vcd-cli/blob/d0d541687a308b5cdeda4d931ebc31469daed1eb/vcd_cli/vapp.py#L228)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

Am I missing something here? Why is vapp command taking vm name as parameter (resource_type='vm')
</blockquote></details>

see my comment above

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150)*

**Comment by rocknes** [comment]
Reviewed 18 of 21 files at r1, 3 of 3 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/utils.py, line 170 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1S4kBDerPpAhmiSHVV:-L1S4kBDerPpAhmiSHVW:bf3fg5t) ([raw file](https://github.com/vmware/vcd-cli/blob/0c2312a74c0668f7c9a8b3f2a44910861b9ac5ed/vcd_cli/utils.py#L170)):*
> ```Python
>                     else:
>                         client = ctx.obj['client']
>                         # last_message = ''
> ```

We should get rid of dead code.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150)*

**Comment by rocknes** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 4 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-:-L1S5e_hw8sFYMxcyp7P:bnfp4nl)*

**Comment by pacogomez** [comment]
Review status: 20 of 21 files reviewed at latest revision, 4 unresolved discussions.

---

*[vcd_cli/utils.py, line 170 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/150#-L1S4kBDerPpAhmiSHVV:-L1T6pqBQJj_GooihJfB:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/0c2312a74c0668f7c9a8b3f2a44910861b9ac5ed/vcd_cli/utils.py#L170)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should get rid of dead code.
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/150)*

**Pull request merged**
