### PR TITLE
Add or Remove rights from a given role

### PR DESCRIPTION
**Pull request by sahithi**
Add or Remove rights from a given role

Example:
To begin with, Role 'vApp User' has zero rights.
>vcd role add-right 'vApp User' 'vApp: Copy' 'vApp: Edit VM CPU'
List of rights in the role 'vApp User':
name
========
vApp: Copy
vApp: Edit VM CPU

>vcd role remove-right 'vApp User' 'vApp: Copy' 
List of rights in the role 'vApp User':
name
=======
vApp: Edit VM CPU

---
This change is [Reviewable](https://reviewable.io/reviews/vmware/vcd-cli/157)

### CODE REVIEW

**Comment by sompa** [comment]
:lgtm:

---







*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L277kV9d8Dpw01vIPgz:bnfp4nl)*

**Comment by sompa** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions, all commit checks successful.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L273D3BJM7mwOSZDa0N:bsvn8ph) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
> ```Python
> def add_right(ctx, role_name, rights, org_name):
>     try:
>         if not is_sysadmin(ctx):
> ```

it would be better if this is thrown by the api call itself and captured by the except catch below in this try block. We would need to augment `stderr` to understand this user is not allowed to run this command. That way we could avoid adding this code to every command that needs sysadmin access.

---

*[vcd_cli/role.py, line 263 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L274BmrQuwL-exz9nNU:-L274BmrQuwL-exz9nNV:b-ktm7n6) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L263)):*
> ```Python
>             raise Exception("Only System administrator can"
>                             " execute this command")
>         if len(rights) < 1:
> ```

see the note about variadic arguments in click: http://click.pocoo.org/5/arguments/#variadic-arguments. I think we should stay away from making individual validations in the code and have a general way to work with exceptions

---

*[vcd_cli/role.py, line 275 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L276kJf3Zusrf_kFMOU:-L276kJf3Zusrf_kFMOV:b-rx3tsy) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L275)):*
> ```Python
>         role_record = org.get_role(role_name)
>         role = Role(client, href=role_record.get('href'))
>         right_records = []
> ```

I would prefer to add a method to `Role` that takes a list of strings and does this processing. That method will be used here and by other clients

---

*[vcd_cli/role.py, line 280 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L277I8v-o5bLacw8P_t:-L277I8v-o5bLacw8P_u:blbkky3) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L280)):*
> ```Python
>             right_records.append(record)
>         updated_role_resource = role.add_rights(right_records)
>         updated_role = Role(client, resource=updated_role_resource)
> ```

I think we should design the commands to do simple and atomic actions. This command adds a right to a role, so it shouldn't also list the current roles. It should return the response from vCD when adding rights or maybe a short message like 'rights added' or just nothing if it was successful (that's also an option). If it fails it should display the error message

---

*[vcd_cli/role.py, line 287 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L278PN-lFBbtsW2hFBH:-L278PN0ZrQ7cNd7E5CJ:b-o6b7kb) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L287)):*
> ```Python
> 
> 
> @role.command('remove-right', short_help='Removes one or more rights'
> ```

see my comments on the `add-right` command

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by pacogomez** [comment]
Review status: all files reviewed at latest revision, 5 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L278z_4MeD03WN3_mrT:b-8edls9) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

it would be better if this is thrown by the api call itself and captured by the except catch below in this try block. We would need to augment `stderr` to understand this user is not allowed to run this command. That way we could avoid adding this code to every command that needs sysadmin access.
</blockquote></details>

By the API call, I mean vCD, the REST API response, not the pyvcloud method.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by anusuyar** [comment]
what about commands like `vcd role right add <args>` `vcd role right remove <args>` instead? This would follow `vcd Entity Sub-Entity verb` pattern we follow with acl.

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 6 unresolved discussions.

---

*[vcd_cli/role.py, line 252 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L27zzn3stXKIxfwh6AO:-L27zzn3stXKIxfwh6AP:bw96ldr) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L252)):*
> ```Python
>                 nargs=-1,
>                 required=True,
>                 metavar='<rights>')
> ```

Removing the metavar here would allow the click to show that this a var-arg in help
something like this.
vcd role add-right [OPTIONS] <role-name> Rights...

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L27webVyTpdrfxndnbt:b-b3ijkt)*

**Comment by rocknes** [comment]
I think we should model these commands around how we are modeling vapp-vm commands,
like adding vms to vapps, removing vms from vapp. 

Entity-acl relationship is a bit different, strictly speaking in terms of semantics (however we do follow the same command pattern for them too). 

---

Review status: all files reviewed at latest revision, 8 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L2GCILYcap_3YefqNxz:bb79kh9) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

By the API call, I mean vCD, the REST API response, not the pyvcloud method.
</blockquote></details>

^ +1

---

*[vcd_cli/role.py, line 275 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L276kJf3Zusrf_kFMOU:-L2GDa7SU_ZEYdPG2YLy:bydlesd) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L275)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I would prefer to add a method to `Role` that takes a list of strings and does this processing. That method will be used here and by other clients
</blockquote></details>

We should probably modify add_rights to take a list of right names rather than list of right records.
pyvcloud can do all the hard work of gathering href from the name of rights.

In future we will beef up our typed query in pyvcloud:client.py to take multiple filters and logical operators,  that way multiple vcd rest calls for getting right records can be compressed into one rest call. And if these call(s) happen in pyvcloud, all the clients can be spared of the optimizations.

---

*[vcd_cli/role.py, line 22 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2G8akMjOEVMoUJbOu2:-L2G8akNudmPv7LkZ3y8:bkds6nk) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L22)):*
> ```Python
> \b
>     Description
>        All sub-commands execute in the context of specified organization;
> ```

This paragraph looks less like description and more like info :(

Also I think the first line should start with mentioning the param (else 'specified organization' makes little sense) and then state what happens if the param is not specified by user.

---

*[vcd_cli/role.py, line 269 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2GC_XW3yT-oeXkeuPV:-L2GC_XW3yT-oeXkeuPW:b-pph6ml) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L269)):*
> ```Python
>         else:
>             org_href = ctx.obj['profiles'].get('org_href')
>         org = Org(client, org_href)
> ```

href=org_href

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L2G9XDb5JBERxwaXOKl:blaggq4)*

**Comment by anusuyar** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by anusuyar** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/role.py, line 22 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2G8akMjOEVMoUJbOu2:-L2N4YcbZ6STLUsB9i04:b59963k) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L22)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This paragraph looks less like description and more like info :(

Also I think the first line should start with mentioning the param (else 'specified organization' makes little sense) and then state what happens if the param is not specified by user.
</blockquote></details>

+1. It should be something like `Work with role of an org`. and then add more details to it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by sahithi** [comment]
Anusuya, 
This command is fairly simple and I dont think there is a need for additional 2 levels of sub commands.

---

Review status: 0 of 1 files reviewed at latest revision, 9 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L2Mx3wP74LprShJLZu1:bquqvfa) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

^ +1
</blockquote></details>

For now, I can get rid of this extra check here to keep it consistent with existing commands.
However, I would like to add this to our design discussion list as multiple rest-api calls can be prevented by an early check. This can really improve performance of scripts based on vcd-cli.

---

*[vcd_cli/role.py, line 263 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L274BmrQuwL-exz9nNU:-L2My16oRL4zp8DAQdMc:b-q2dn9j) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L263)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

see the note about variadic arguments in click: http://click.pocoo.org/5/arguments/#variadic-arguments. I think we should stay away from making individual validations in the code and have a general way to work with exceptions
</blockquote></details>

I was already using this.

---

*[vcd_cli/role.py, line 275 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L276kJf3Zusrf_kFMOU:-L2NCAvgIzOVmcD8O4i7:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L275)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

We should probably modify add_rights to take a list of right names rather than list of right records.
pyvcloud can do all the hard work of gathering href from the name of rights.

In future we will beef up our typed query in pyvcloud:client.py to take multiple filters and logical operators,  that way multiple vcd rest calls for getting right records can be compressed into one rest call. And if these call(s) happen in pyvcloud, all the clients can be spared of the optimizations.
</blockquote></details>

Done.

---

*[vcd_cli/role.py, line 280 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L277I8v-o5bLacw8P_t:-L2N08MyVEDB6iO38627:b2lxutg) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L280)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I think we should design the commands to do simple and atomic actions. This command adds a right to a role, so it shouldn't also list the current roles. It should return the response from vCD when adding rights or maybe a short message like 'rights added' or just nothing if it was successful (that's also an option). If it fails it should display the error message
</blockquote></details>

I tried printing the role itself but it wouldn't display its list of rights. So I wrote few extra lines of code to list rights. Anyway, I don't mind removing it and will conclude it with a simple message "Rights added.."

---

*[vcd_cli/role.py, line 287 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L278PN-lFBbtsW2hFBH:-L2NC_cIxX3LuwOhwwrA:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L287)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

see my comments on the `add-right` command
</blockquote></details>

Done.

---

*[vcd_cli/role.py, line 22 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2G8akMjOEVMoUJbOu2:-L2MwRj2vg6XPaa-M5z6:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L22)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

This paragraph looks less like description and more like info :(

Also I think the first line should start with mentioning the param (else 'specified organization' makes little sense) and then state what happens if the param is not specified by user.
</blockquote></details>

Done.

---

*[vcd_cli/role.py, line 252 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L27zzn3stXKIxfwh6AO:-L2MwxldxRQu_1S61f9-:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L252)):*
<details><summary><i>Previously, anusuyar wrote…</i></summary><blockquote>

Removing the metavar here would allow the click to show that this a var-arg in help
something like this.
vcd role add-right [OPTIONS] <role-name> Rights...
</blockquote></details>

Done.

---

*[vcd_cli/role.py, line 269 at r2](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2GC_XW3yT-oeXkeuPV:-L2My04Rcfow5EGYtSFi:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/dac1c8b51d14b4fe2cbcf30a760a599ba17e9319/vcd_cli/role.py#L269)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

href=org_href
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L2MFFGYW1Dmx67lMva-:b-4ulyz)*

**Comment by anusuyar** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r3.
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L2NHGSfsovkKzJshdwt:bnfp4nl)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 7 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L2NKBdZ4BRIWzrnIsss:b-ind2ur) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, sahithi (Sahithi Ayloo) wrote…</i></summary><blockquote>

For now, I can get rid of this extra check here to keep it consistent with existing commands.
However, I would like to add this to our design discussion list as multiple rest-api calls can be prevented by an early check. This can really improve performance of scripts based on vcd-cli.
</blockquote></details>

Is this operation really restricted to sysadmin?  I thought most  vCD operations were based on privileges.  If it is possible for accounts other than sysadmin to have the privilege then this check would deny access to an otherwise privileged user. 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by pacogomez** [comment]
at some point I think there should be common pattern shared by all the commands, so users should be able to remember or predict the right syntax for all commands without having to remember the special cases.

---

Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L2OcFb6021hwnnusq9j:b-ax0e2k) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, hodgesrm (Robert Hodges) wrote…</i></summary><blockquote>

Is this operation really restricted to sysadmin?  I thought most  vCD operations were based on privileges.  If it is possible for accounts other than sysadmin to have the privilege then this check would deny access to an otherwise privileged user. 
</blockquote></details>

I understand the call optimization but I think we should let vCD validate the access.

---

*[vcd_cli/role.py, line 22 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2OZYjnP5xDI6Qpt_21:-L2OZYjnP5xDI6Qpt_22:b-y0x870) ([raw file](https://github.com/vmware/vcd-cli/blob/7eab183fe461a78d865cd76a300a7d723fbb94e9/vcd_cli/role.py#L22)):*
> ```Python
> \b
>     Note
>        All sub-commands execute in the context of organization specified
> ```

a general brief description of what it means to work with roles should precede the clarification about org

---

*[vcd_cli/role.py, line 155 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2OZuC_PWRw-rsKTYMl:-L2OZuC_PWRw-rsKTYMm:b-yvvatw) ([raw file](https://github.com/vmware/vcd-cli/blob/7eab183fe461a78d865cd76a300a7d723fbb94e9/vcd_cli/role.py#L155)):*
> ```Python
> 
> @role.command('delete', short_help='Deletes role in the specified Organization'
>                                    '(defaults to the current org in use')
> ```

it is not necessary to clarify this in the short help

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L2OYYM0nZjJ0Ne-IvrF:b11cogm)*

**Comment by rocknes** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L2NQsrxmepS3-qVV7E3:be07u0o) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

I understand the call optimization but I think we should let vCD validate the access.
</blockquote></details>

@Robert, vcd rights pertaining to sys-admin operations are not as granular as we might believe. A lot of rights are actually roled into a singular right called sys_admin_only

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by hodgesrm** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions.

---

*[vcd_cli/role.py, line 260 at r1](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L273D3BJM7mwOSZDa0M:-L2Qh8CiV-_5Mp2nAZ-w:b-il0d59) ([raw file](https://github.com/vmware/vcd-cli/blob/79ab52f0d23b3e91574ae749808f5cff0d68ce9e/vcd_cli/role.py#L260)):*
<details><summary><i>Previously, rocknes wrote…</i></summary><blockquote>

@Robert, vcd rights pertaining to sys-admin operations are not as granular as we might believe. A lot of rights are actually roled into a singular right called sys_admin_only
</blockquote></details>

Thanks @rocknes.  On a related note I believe Paco is right that we should not put security checks into vcd-cli.  We're tying client code to a security model we don't own and that will certainly change in future releases (much as it has changed in the past). 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by sahithi** [comment]
Review status: all files reviewed at latest revision, 3 unresolved discussions, some commit checks failed.

---

*[vcd_cli/role.py, line 22 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2OZYjnP5xDI6Qpt_21:-L2RKugytUndENLzuPTN:b-3tlgd4) ([raw file](https://github.com/vmware/vcd-cli/blob/7eab183fe461a78d865cd76a300a7d723fbb94e9/vcd_cli/role.py#L22)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

a general brief description of what it means to work with roles should precede the clarification about org
</blockquote></details>

Summary is already present.
As all commands are self-explanatory I don't see a need to add additional description. Just followed the pattern from other commands.

---

*[vcd_cli/role.py, line 155 at r3](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-L2OZuC_PWRw-rsKTYMl:-L2RKsSrQYq0kS0KGtr6:b-896fix) ([raw file](https://github.com/vmware/vcd-cli/blob/7eab183fe461a78d865cd76a300a7d723fbb94e9/vcd_cli/role.py#L155)):*
<details><summary><i>Previously, pacogomez (Paco Gómez) wrote…</i></summary><blockquote>

it is not necessary to clarify this in the short help
</blockquote></details>

Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157)*

**Comment by pacogomez** [comment]
:lgtm:

---

Reviewed 1 of 1 files at r4.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/vmware/vcd-cli/157#-:-L2TXg7GJ1TQA7CSVHq6:bnfp4nl)*

**Pull request merged**
